import { z } from 'zod'
import {
  SPACEX_DEFAULT_LAUNCH_SORT,
  SPACEX_DEFAULT_LIMIT,
  SPACEX_MAX_LIMIT,
  SPACEX_MAX_PAGE,
  getSpaceXCompany,
  listSpaceXLaunches,
  listSpaceXLaunchpads,
  listSpaceXRockets,
  normalizeSpaceXCompanyInput,
  normalizeSpaceXLaunchesInput,
  normalizeSpaceXLaunchpadsInput,
  normalizeSpaceXRocketsInput,
  type SpaceXCompanyInput,
  type SpaceXLaunchesInput,
  type SpaceXListInput,
} from '../../application/usecases/spaceX.js'
import type {
  PublicApiOperationDefinition,
  PublicApiProviderModule,
} from '../providerTypes.js'

const companyParamsSchema = z.object({}) satisfies z.ZodType<SpaceXCompanyInput>

const listParamsSchema = z.object({
  search: z.string().optional(),
  active: z.boolean().optional(),
  status: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
}) satisfies z.ZodType<SpaceXListInput>

const launchesParamsSchema = z.object({
  name: z.string().optional(),
  upcoming: z.boolean().optional(),
  success: z.boolean().optional(),
  rocket: z.string().optional(),
  launchpad: z.string().optional(),
  start: z.string().optional(),
  end: z.string().optional(),
  sort: z.string().optional(),
  limit: z.number().int().optional(),
  page: z.number().int().optional(),
}) satisfies z.ZodType<SpaceXLaunchesInput>

const companyOperation: PublicApiOperationDefinition<SpaceXCompanyInput> = {
  id: 'spacex.company',
  providerId: 'spacex',
  name: 'Company',
  commandPath: ['spacex', 'company'],
  rpcMethod: 'spacex.company',
  description: 'Show SpaceX company metadata from the public REST API.',
  category: 'science',
  options: [],
  paramsSchema: companyParamsSchema,
  execute: params => getSpaceXCompany(params),
  normalizeParams: params => companyParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeSpaceXCompanyInput(params),
  resultKind: 'spacex.company',
  defaultFormat: 'text',
}

const rocketsOperation: PublicApiOperationDefinition<SpaceXListInput> = {
  id: 'spacex.rockets',
  providerId: 'spacex',
  name: 'Rockets',
  commandPath: ['spacex', 'rockets'],
  rpcMethod: 'spacex.rockets',
  description: 'List SpaceX rocket metadata with local filters.',
  category: 'science',
  options: [
    {
      name: 'search',
      flag: '--search <text>',
      description: 'Local search over rocket names, country, company, and description.',
      exposure: 'primary',
      group: 'query',
      reason: [
        'Rockets are a small public list; local filtering avoids raw query',
        'proxying.',
      ].join(' '),
    },
    {
      name: 'active',
      flag: '--active <true|false>',
      description: 'Filter active or inactive rockets.',
      exposure: 'primary',
      group: 'filters',
      reason: 'The active field is a stable documented rocket attribute.',
      valueType: 'boolean',
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: [
        `Rows to show, default ${SPACEX_DEFAULT_LIMIT},`,
        `cap ${SPACEX_MAX_LIMIT}.`,
      ].join(' '),
      exposure: 'primary',
      group: 'pagination',
      reason: 'Terminal output and persistence payloads stay bounded.',
      valueType: 'integer',
      defaultValue: String(SPACEX_DEFAULT_LIMIT),
    },
    {
      name: 'offset',
      flag: '--offset <count>',
      description: 'Rows to skip in the local filtered list, default 0.',
      exposure: 'advanced',
      group: 'pagination',
      reason: 'Provides local navigation without exposing raw upstream query options.',
      valueType: 'integer',
      defaultValue: '0',
    },
  ],
  paramsSchema: listParamsSchema,
  execute: params => listSpaceXRockets(params),
  normalizeParams: params => listParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeSpaceXRocketsInput(params),
  resultKind: 'spacex.rockets',
  defaultFormat: 'text',
}

const launchpadsOperation: PublicApiOperationDefinition<SpaceXListInput> = {
  id: 'spacex.launchpads',
  providerId: 'spacex',
  name: 'Launchpads',
  commandPath: ['spacex', 'launchpads'],
  rpcMethod: 'spacex.launchpads',
  description: 'List SpaceX launchpad metadata with local filters.',
  category: 'science',
  options: [
    {
      name: 'search',
      flag: '--search <text>',
      description: 'Local search over launchpad names, locality, region, and status.',
      exposure: 'primary',
      group: 'query',
      reason: 'Launchpads are a small public list; local filtering is predictable.',
    },
    {
      name: 'status',
      flag: '--status <status>',
      description: 'Optional launchpad status filter such as active or retired.',
      exposure: 'primary',
      group: 'filters',
      reason: 'Status is a stable documented launchpad attribute.',
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: [
        `Rows to show, default ${SPACEX_DEFAULT_LIMIT},`,
        `cap ${SPACEX_MAX_LIMIT}.`,
      ].join(' '),
      exposure: 'primary',
      group: 'pagination',
      reason: 'Terminal output and persistence payloads stay bounded.',
      valueType: 'integer',
      defaultValue: String(SPACEX_DEFAULT_LIMIT),
    },
    {
      name: 'offset',
      flag: '--offset <count>',
      description: 'Rows to skip in the local filtered list, default 0.',
      exposure: 'advanced',
      group: 'pagination',
      reason: 'Provides local navigation without exposing raw upstream query options.',
      valueType: 'integer',
      defaultValue: '0',
    },
  ],
  paramsSchema: listParamsSchema,
  execute: params => listSpaceXLaunchpads(params),
  normalizeParams: params => listParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeSpaceXLaunchpadsInput(params),
  resultKind: 'spacex.launchpads',
  defaultFormat: 'text',
}

const launchesOperation: PublicApiOperationDefinition<SpaceXLaunchesInput> = {
  id: 'spacex.launches',
  providerId: 'spacex',
  name: 'Launches',
  commandPath: ['spacex', 'launches'],
  rpcMethod: 'spacex.launches',
  description: 'Query SpaceX launch metadata with bounded curated filters.',
  category: 'science',
  options: [
    {
      name: 'name',
      flag: '--name <text>',
      description: 'Case-insensitive launch name match.',
      exposure: 'primary',
      group: 'query',
      reason: 'Name search is useful and compiled into a bounded regex filter.',
    },
    {
      name: 'upcoming',
      flag: '--upcoming <true|false>',
      description: 'Filter upcoming or historical launches.',
      exposure: 'primary',
      group: 'filters',
      reason: 'The upcoming boolean is a stable documented launch attribute.',
      valueType: 'boolean',
    },
    {
      name: 'success',
      flag: '--success <true|false>',
      description: 'Filter successful or failed historical launches.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'The success boolean is useful for historical launch analysis.',
      valueType: 'boolean',
    },
    {
      name: 'rocket',
      flag: '--rocket <id>',
      description: 'Filter by a 24 character SpaceX rocket id.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Rocket id is documented on launch records and avoids name ambiguity.',
    },
    {
      name: 'launchpad',
      flag: '--launchpad <id>',
      description: 'Filter by a 24 character SpaceX launchpad id.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Launchpad id is documented on launch records and avoids name ambiguity.',
    },
    {
      name: 'start',
      flag: '--start <iso>',
      description: 'Earliest UTC launch date, YYYY-MM-DD or UTC ISO.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Date windows bound query result sets without raw query JSON.',
    },
    {
      name: 'end',
      flag: '--end <iso>',
      description: 'Latest UTC launch date, YYYY-MM-DD or UTC ISO.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Date windows bound query result sets without raw query JSON.',
    },
    {
      name: 'sort',
      flag: '--sort <date-desc|date-asc|flight-desc|flight-asc>',
      description: `Curated sort, default ${SPACEX_DEFAULT_LAUNCH_SORT}.`,
      exposure: 'advanced',
      group: 'presentation',
      reason: 'Maps to a fixed sort object instead of arbitrary options passthrough.',
      defaultValue: SPACEX_DEFAULT_LAUNCH_SORT,
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: [
        `Rows to request, default ${SPACEX_DEFAULT_LIMIT},`,
        `cap ${SPACEX_MAX_LIMIT}.`,
      ].join(' '),
      exposure: 'primary',
      group: 'pagination',
      reason: 'Uses bounded query options for readable terminal output.',
      valueType: 'integer',
      defaultValue: String(SPACEX_DEFAULT_LIMIT),
    },
    {
      name: 'page',
      flag: '--page <number>',
      description: `Query page, default 1, cap ${SPACEX_MAX_PAGE}.`,
      exposure: 'advanced',
      group: 'pagination',
      reason: 'Uses documented query pagination while bounding traversal.',
      valueType: 'integer',
      defaultValue: '1',
    },
  ],
  paramsSchema: launchesParamsSchema,
  execute: params => listSpaceXLaunches(params),
  normalizeParams: params => launchesParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeSpaceXLaunchesInput(params),
  resultKind: 'spacex.launches',
  defaultFormat: 'text',
}

export const spaceXProvider: PublicApiProviderModule = {
  manifest: {
    id: 'spacex',
    name: 'SpaceX REST',
    description: [
      'No-auth HTTPS JSON provider for SpaceX company, rocket, launchpad,',
      'and launch metadata from the r-spacex REST API.',
    ].join(' '),
    publicApisCategory: 'Science & Math',
    homepageUrl: 'https://github.com/r-spacex/SpaceX-API',
    docsUrl: 'https://github.com/r-spacex/SpaceX-API/tree/master/docs',
    auth: {
      mode: 'none',
      notes: [
        [
          'Official selected read-only docs mark Auth required False and live',
          'probes returned JSON without API key, OAuth, account, cookies, or',
          'browser clickstream.',
        ].join(' '),
        'Mutating create/update/delete routes require spacex-key and are excluded.',
      ],
    },
    tags: [
      'science',
      'spaceflight',
      'spacex',
      'rockets',
      'launches',
      'launchpads',
      'json',
      'no-auth',
    ],
    freePlanNotes: [
      'No public quota was found for selected read-only REST routes.',
      [
        'CLI exposes curated read-only metadata only; raw Mongo/Mongoose query',
        'JSON, GraphQL, mutations, image downloads, and scraping are excluded.',
      ].join(' '),
    ],
  },
  operations: [
    companyOperation,
    rocketsOperation,
    launchpadsOperation,
    launchesOperation,
  ],
  endpoints: [
    {
      id: 'spacex-company',
      method: 'GET',
      urlPattern: 'https://api.spacexdata.com/v4/company',
      category: 'public-apis:science',
      evidenceStatus: 'confirmed',
      observedOn: '2026-05-11',
      description: 'SpaceX REST company metadata endpoint.',
      sampleSources: [
        'https://github.com/r-spacex/SpaceX-API/blob/master/docs/company/v4/all.md',
      ],
      consumedBy: ['spacex.company'],
      notes: ['No auth; mutating spacex-key routes are excluded.'],
    },
    {
      id: 'spacex-rockets',
      method: 'GET',
      urlPattern: 'https://api.spacexdata.com/v4/rockets',
      category: 'public-apis:science',
      evidenceStatus: 'confirmed',
      observedOn: '2026-05-11',
      description: 'SpaceX REST rocket list endpoint.',
      sampleSources: [
        'https://github.com/r-spacex/SpaceX-API/blob/master/docs/rockets/v4/all.md',
      ],
      consumedBy: ['spacex.rockets'],
      notes: ['No auth; CLI filters the small returned list locally.'],
    },
    {
      id: 'spacex-launchpads',
      method: 'GET',
      urlPattern: 'https://api.spacexdata.com/v4/launchpads',
      category: 'public-apis:science',
      evidenceStatus: 'confirmed',
      observedOn: '2026-05-11',
      description: 'SpaceX REST launchpad list endpoint.',
      sampleSources: [
        'https://github.com/r-spacex/SpaceX-API/blob/master/docs/launchpads/v4/all.md',
      ],
      consumedBy: ['spacex.launchpads'],
      notes: ['No auth; CLI filters the small returned list locally.'],
    },
    {
      id: 'spacex-launches-query',
      method: 'POST',
      urlPattern: 'https://api.spacexdata.com/v5/launches/query',
      category: 'public-apis:science',
      evidenceStatus: 'confirmed',
      observedOn: '2026-05-11',
      description: 'SpaceX REST launch query endpoint with curated body.',
      sampleSources: [
        'https://github.com/r-spacex/SpaceX-API/blob/master/docs/launches/v5/query.md',
      ],
      consumedBy: ['spacex.launches'],
      notes: [
        [
          'No auth; raw query/options JSON and arbitrary Mongoose operators are',
          'not exposed by the CLI.',
        ].join(' '),
      ],
    },
  ],
}
