import { z } from 'zod'
import {
  getOpenLibraryWork,
  searchOpenLibrary,
  type OpenLibrarySearchInput,
  type OpenLibraryWorkInput,
} from '../../application/usecases/openLibrary.js'
import type { PublicApiOperationDefinition, PublicApiProviderModule } from '../providerTypes.js'

const searchParamsSchema = z.object({
  query: z.string().min(1).optional(),
  title: z.string().min(1).optional(),
  author: z.string().min(1).optional(),
  subject: z.string().min(1).optional(),
  language: z.string().min(1).optional(),
  hasFulltext: z.boolean().optional(),
  ebookAccess: z.string().min(1).optional(),
  sort: z.string().min(1).optional(),
  page: z.number().int().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
}) satisfies z.ZodType<OpenLibrarySearchInput>

const workParamsSchema = z.object({
  workKey: z.string().min(1).optional(),
}) satisfies z.ZodType<OpenLibraryWorkInput>

const searchOperation: PublicApiOperationDefinition<OpenLibrarySearchInput> = {
  id: 'openlibrary.search',
  providerId: 'openlibrary',
  name: 'Search works',
  commandPath: ['openlibrary', 'search'],
  rpcMethod: 'openlibrary.search',
  description: 'Search Open Library work metadata using the documented Search API.',
  category: 'books',
  options: [
    {
      name: 'query',
      flag: '--query <text>',
      description: 'General search query, default pride and prejudice',
      exposure: 'primary',
      group: 'query',
      reason: 'The Search API q parameter is the primary discovery workflow for terminal users.',
      defaultValue: 'pride and prejudice',
    },
    {
      name: 'title',
      flag: '--title <text>',
      description: 'Restrict search to title text',
      exposure: 'primary',
      group: 'query',
      reason: 'Title search is documented and useful for precise book lookup.',
    },
    {
      name: 'author',
      flag: '--author <name>',
      description: 'Restrict search to author name',
      exposure: 'primary',
      group: 'query',
      reason: 'Author search is documented and high-value for book discovery.',
    },
    {
      name: 'subject',
      flag: '--subject <text>',
      description: 'Filter by subject/topic',
      exposure: 'primary',
      group: 'filters',
      reason: 'Subject filtering is documented and useful for browsing collections.',
    },
    {
      name: 'language',
      flag: '--language <code>',
      description: 'Filter by ISO language code such as eng',
      exposure: 'primary',
      group: 'filters',
      reason: 'Language filtering is documented and makes terminal results more relevant.',
    },
    {
      name: 'hasFulltext',
      flag: '--has-fulltext <true|false>',
      description: 'Filter by full-text availability',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Full-text availability is useful but secondary to basic discovery.',
      valueType: 'boolean',
    },
    {
      name: 'ebookAccess',
      flag: '--ebook-access <public|borrowable|printdisabled|no_ebook>',
      description: 'Filter by e-book access type',
      exposure: 'advanced',
      group: 'filters',
      reason: 'E-book access filtering is documented but has provider-specific values.',
    },
    {
      name: 'sort',
      flag: '--sort <relevance|new|old|random|key|title>',
      description: 'Sort order, default provider relevance',
      exposure: 'advanced',
      group: 'presentation',
      reason: 'Sort is documented but not needed for the default discovery path.',
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: 'Results to request/show, default 100, CLI cap 100',
      exposure: 'primary',
      group: 'pagination',
      reason: 'Docs state 100 results per page by default; exposing it lets users control output size.',
      valueType: 'integer',
      defaultValue: '100',
    },
    {
      name: 'page',
      flag: '--page <number>',
      description: 'Provider page number',
      exposure: 'advanced',
      group: 'pagination',
      reason: 'Open Library supports page pagination, but offset is clearer for replay and cache keys.',
      valueType: 'integer',
    },
    {
      name: 'offset',
      flag: '--offset <count>',
      description: 'Result offset for paging',
      exposure: 'advanced',
      group: 'pagination',
      reason: 'Offset is documented and useful for exact offline replay of paged searches.',
      valueType: 'integer',
    },
  ],
  paramsSchema: searchParamsSchema,
  execute: params => searchOpenLibrary(params),
  normalizeParams: params => searchParamsSchema.parse(params),
  resultKind: 'openlibrary.search',
  defaultFormat: 'text',
}

const workOperation: PublicApiOperationDefinition<OpenLibraryWorkInput> = {
  id: 'openlibrary.work',
  providerId: 'openlibrary',
  name: 'Work',
  commandPath: ['openlibrary', 'work'],
  rpcMethod: 'openlibrary.work',
  description: 'Fetch one Open Library work JSON document by work key.',
  category: 'books',
  options: [
    {
      name: 'workKey',
      flag: '--work-key <key>',
      description: 'Work key such as OL66554W or /works/OL66554W, default OL66554W',
      exposure: 'primary',
      group: 'query',
      reason: 'The work endpoint is key-addressed; accepting common key forms improves CLI usability.',
      defaultValue: 'OL66554W',
    },
  ],
  paramsSchema: workParamsSchema,
  execute: params => getOpenLibraryWork(params),
  normalizeParams: params => workParamsSchema.parse(params),
  createCacheKeyParams: params => ({ workKey: params.workKey ?? 'OL66554W' }),
  resultKind: 'openlibrary.work',
  defaultFormat: 'text',
}

export const openLibraryProvider: PublicApiProviderModule = {
  manifest: {
    id: 'openlibrary',
    name: 'Open Library',
    description: 'No-auth HTTPS JSON APIs for searching books and reading Open Library work metadata.',
    publicApisCategory: 'Books',
    homepageUrl: 'https://openlibrary.org/',
    docsUrl: 'https://openlibrary.org/developers/api',
    auth: {
      mode: 'none',
      notes: ['Official developer docs expose public JSON endpoints without API keys for search and works.'],
    },
    tags: ['books', 'metadata', 'covers', 'works', 'no-auth'],
    freePlanNotes: [
      'Search API docs state it returns 100 results per page by default; CLI defaults and caps --limit at 100 for terminal/cache safety.',
      'Open Library asks clients to identify themselves with a User-Agent; the client sends a CLI User-Agent.',
    ],
  },
  operations: [searchOperation, workOperation],
  endpoints: [
    {
      id: 'openlibrary-search',
      method: 'GET',
      urlPattern: 'https://openlibrary.org/search.json',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Open Library Search API for work/book discovery.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://openlibrary.org/dev/docs/api/search'],
      consumedBy: ['openlibrary search'],
      notes: ['No authentication required; CLI sends fields to keep payloads bounded.'],
    },
    {
      id: 'openlibrary-work',
      method: 'GET',
      urlPattern: 'regex:^https://openlibrary\\.org/works/OL[0-9]+W\\.json$',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Open Library REST work JSON resource.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://openlibrary.org/dev/docs/api/books'],
      consumedBy: ['openlibrary work'],
      notes: ['No authentication required; work keys are normalized before request and persistence.'],
    },
  ],
}
