import { z } from 'zod'
import {
  getPoetryDbRandom,
  searchPoetryDb,
  type PoetryDbRandomInput,
  type PoetryDbSearchInput,
} from '../../application/usecases/poetryDb.js'
import type { PublicApiOperationDefinition, PublicApiProviderModule } from '../providerTypes.js'

const searchParamsSchema = z.object({
  field: z.enum(['author', 'title', 'lines', 'linecount']).optional(),
  term: z.string().min(1).optional(),
  exact: z.boolean().optional(),
  count: z.number().int().optional(),
  includeLines: z.boolean().optional(),
  lineLimit: z.number().int().optional(),
}) satisfies z.ZodType<PoetryDbSearchInput>

const randomParamsSchema = z.object({
  count: z.number().int().optional(),
  includeLines: z.boolean().optional(),
  lineLimit: z.number().int().optional(),
}) satisfies z.ZodType<PoetryDbRandomInput>

const searchOperation: PublicApiOperationDefinition<PoetryDbSearchInput> = {
  id: 'poetrydb.search',
  providerId: 'poetrydb',
  name: 'Search poems',
  commandPath: ['poetrydb', 'search'],
  rpcMethod: 'poetrydb.search',
  description: 'Search PoetryDB poems by one curated field and return terminal-friendly poem metadata.',
  category: 'books',
  options: [
    {
      name: 'field',
      flag: '--field <author|title|lines|linecount>',
      description: 'Search field, default title',
      exposure: 'primary',
      group: 'query',
      reason: 'PoetryDB route grammar is field-driven; exposing one field keeps CLI UX clear.',
      defaultValue: 'title',
    },
    {
      name: 'term',
      flag: '--term <text>',
      description: 'Search term, default Ozymandias',
      exposure: 'primary',
      group: 'query',
      reason: 'The route requires a search term for author/title/lines/linecount lookup.',
      defaultValue: 'Ozymandias',
    },
    {
      name: 'exact',
      flag: '--exact <true|false>',
      description: 'Use documented :abs exact match, default false',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Exact matching is documented but secondary to forgiving terminal search.',
      valueType: 'boolean',
      defaultValue: 'false',
    },
    {
      name: 'count',
      flag: '--count <count>',
      description: 'Poems to request via poemcount, default 20, CLI cap 20',
      exposure: 'primary',
      group: 'pagination',
      reason: 'PoetryDB documents poemcount; a bounded count keeps output/cache safe.',
      valueType: 'integer',
      defaultValue: '20',
    },
    {
      name: 'includeLines',
      flag: '--include-lines <true|false>',
      description: 'Include poem lines in response, default true',
      exposure: 'primary',
      group: 'content',
      reason: 'Poem lines are the main content, but users may request metadata-only output.',
      valueType: 'boolean',
      defaultValue: 'true',
    },
    {
      name: 'lineLimit',
      flag: '--line-limit <count>',
      description: 'Maximum lines shown/cache per poem, default 12, cap 80',
      exposure: 'advanced',
      group: 'presentation',
      reason: 'Some poems are long; limiting lines preserves readable TUI and bounded persistence.',
      valueType: 'integer',
      defaultValue: '12',
    },
  ],
  paramsSchema: searchParamsSchema,
  execute: params => searchPoetryDb(params),
  normalizeParams: params => searchParamsSchema.parse(params),
  resultKind: 'poetrydb.search',
  defaultFormat: 'text',
}

const randomOperation: PublicApiOperationDefinition<PoetryDbRandomInput> = {
  id: 'poetrydb.random',
  providerId: 'poetrydb',
  name: 'Random poems',
  commandPath: ['poetrydb', 'random'],
  rpcMethod: 'poetrydb.random',
  description: 'Fetch random PoetryDB poems with curated count and line projection.',
  category: 'books',
  options: [
    {
      name: 'count',
      flag: '--count <count>',
      description: 'Random poems to request, default 1, CLI cap 20',
      exposure: 'primary',
      group: 'pagination',
      reason: 'PoetryDB documents random count; a bounded count keeps output/cache safe.',
      valueType: 'integer',
      defaultValue: '1',
    },
    {
      name: 'includeLines',
      flag: '--include-lines <true|false>',
      description: 'Include poem lines in response, default false',
      exposure: 'primary',
      group: 'content',
      reason: 'Metadata-only random browsing is compact; lines can be enabled explicitly.',
      valueType: 'boolean',
      defaultValue: 'false',
    },
    {
      name: 'lineLimit',
      flag: '--line-limit <count>',
      description: 'Maximum lines shown/cache per poem, default 12, cap 80',
      exposure: 'advanced',
      group: 'presentation',
      reason: 'Some random poems are long; limiting lines preserves readable TUI and bounded persistence.',
      valueType: 'integer',
      defaultValue: '12',
    },
  ],
  paramsSchema: randomParamsSchema,
  execute: params => getPoetryDbRandom(params),
  normalizeParams: params => randomParamsSchema.parse(params),
  resultKind: 'poetrydb.random',
  defaultFormat: 'text',
}

export const poetryDbProvider: PublicApiProviderModule = {
  manifest: {
    id: 'poetrydb',
    name: 'PoetryDB',
    description: 'No-auth HTTPS JSON API for searching poems and fetching random poems.',
    publicApisCategory: 'Books',
    homepageUrl: 'https://poetrydb.org/',
    docsUrl: 'https://github.com/thundercomb/poetrydb#readme',
    auth: {
      mode: 'none',
      notes: ['Official README examples use public HTTPS JSON endpoints without API keys.'],
    },
    tags: ['books', 'poetry', 'poems', 'literature', 'no-auth'],
    freePlanNotes: [
      'README documents poemcount/random count but does not publish a finite maximum; CLI defaults/caps count at 20 for terminal/cache safety.',
      'Default format is JSON; CLI always requests .json and never uses browser scraping.',
    ],
  },
  operations: [searchOperation, randomOperation],
  endpoints: [
    {
      id: 'poetrydb-search',
      method: 'GET',
      urlPattern: 'regex:^https://poetrydb\\.org/(author|title|lines|linecount)/.+',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'PoetryDB field search route with optional poemcount and output fields.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://github.com/thundercomb/poetrydb#readme'],
      consumedBy: ['poetrydb search'],
      notes: ['No authentication required; CLI exposes one curated input field at a time.'],
    },
    {
      id: 'poetrydb-random',
      method: 'GET',
      urlPattern: 'regex:^https://poetrydb\\.org/random(/.+)?',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'PoetryDB random poem route with optional count and output fields.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://github.com/thundercomb/poetrydb#readme'],
      consumedBy: ['poetrydb random'],
      notes: ['No authentication required; CLI caps random count for terminal/cache safety.'],
    },
  ],
}
