import { z } from 'zod'
import {
  listWaifuImImages,
  listWaifuImTags,
  type WaifuImImagesInput,
  type WaifuImTagsInput,
} from '../../application/usecases/waifuIm.js'
import type { PublicApiOperationDefinition, PublicApiProviderModule } from '../providerTypes.js'

const imagesParamsSchema = z.object({
  includedTags: z.string().min(1).optional(),
  excludedTags: z.string().min(1).optional(),
  nsfw: z.string().min(1).optional(),
  animated: z.string().min(1).optional(),
  orderBy: z.string().min(1).optional(),
  orientation: z.string().min(1).optional(),
  page: z.number().int().optional(),
  pageSize: z.number().int().optional(),
}) satisfies z.ZodType<WaifuImImagesInput>

const tagsParamsSchema = z.object({
  name: z.string().min(1).optional(),
  slugs: z.string().min(1).optional(),
  page: z.number().int().optional(),
  pageSize: z.number().int().optional(),
}) satisfies z.ZodType<WaifuImTagsInput>

const imagesOperation: PublicApiOperationDefinition<WaifuImImagesInput> = {
  id: 'waifuim.images',
  providerId: 'waifuim',
  name: 'Images',
  commandPath: ['waifuim', 'images'],
  rpcMethod: 'waifuim.images',
  description: 'Browse Waifu.im images with curated safe filters.',
  category: 'anime',
  options: [
    {
      name: 'includedTags',
      flag: '--included-tags <slugs>',
      description: 'Comma-separated tags that every image must include, such as waifu,maid',
      exposure: 'primary',
      group: 'filters',
      reason: 'Primary content filter for browsing images while preserving documented AND semantics.',
    },
    {
      name: 'excludedTags',
      flag: '--excluded-tags <slugs>',
      description: 'Comma-separated tags to exclude from results',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Useful for refining searches but secondary to include tags.',
    },
    {
      name: 'nsfw',
      flag: '--nsfw <False|True|All>',
      description: 'NSFW filter; default False keeps output safe by default',
      exposure: 'primary',
      group: 'filters',
      reason: 'Safety-critical documented filter that should be explicit in CLI UX.',
      defaultValue: 'False',
    },
    {
      name: 'animated',
      flag: '--animated <False|True|All>',
      description: 'Animation filter; default All',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Useful media filter but not needed for first-run browsing.',
      defaultValue: 'All',
    },
    {
      name: 'orderBy',
      flag: '--order-by <Random|UploadedAt|Favorites>',
      description: 'Documented image ordering; AddedToAlbum is intentionally omitted for public image browsing',
      exposure: 'advanced',
      group: 'presentation',
      reason: 'Sort control is useful but secondary; avoids album-only ordering in the generic images operation.',
      defaultValue: 'Random',
    },
    {
      name: 'orientation',
      flag: '--orientation <All|Landscape|Portrait|Square>',
      description: 'Image orientation filter',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Useful visual filter for terminal workflows that preview image URLs.',
      defaultValue: 'All',
    },
    {
      name: 'page',
      flag: '--page <number>',
      description: 'Page number, default 1',
      exposure: 'advanced',
      group: 'pagination',
      reason: 'Supports documented pagination while keeping first-run help focused.',
      valueType: 'integer',
      defaultValue: '1',
    },
    {
      name: 'pageSize',
      flag: '--page-size <count>',
      description: 'Results per page, 1-100 CLI cap',
      exposure: 'primary',
      group: 'pagination',
      reason: 'Controls response size; docs say unlimited, so CLI caps interactive requests at 100.',
      valueType: 'integer',
      defaultValue: '100',
    },
  ],
  paramsSchema: imagesParamsSchema,
  execute: params => listWaifuImImages(params),
  normalizeParams: params => imagesParamsSchema.parse(params),
  resultKind: 'waifuim.images',
  defaultFormat: 'text',
}

const tagsOperation: PublicApiOperationDefinition<WaifuImTagsInput> = {
  id: 'waifuim.tags',
  providerId: 'waifuim',
  name: 'Tags',
  commandPath: ['waifuim', 'tags'],
  rpcMethod: 'waifuim.tags',
  description: 'List Waifu.im tags with optional name or slug filters.',
  category: 'anime',
  options: [
    {
      name: 'name',
      flag: '--name <text>',
      description: 'Case-insensitive partial tag name filter',
      exposure: 'primary',
      group: 'query',
      reason: 'Primary user intent for tag discovery.',
    },
    {
      name: 'slugs',
      flag: '--slugs <slugs>',
      description: 'Comma-separated exact tag slugs',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Useful exact lookup after a user already knows tag slugs.',
    },
    {
      name: 'page',
      flag: '--page <number>',
      description: 'Page number, default 1',
      exposure: 'advanced',
      group: 'pagination',
      reason: 'Supports documented pagination while keeping first-run help focused.',
      valueType: 'integer',
      defaultValue: '1',
    },
    {
      name: 'pageSize',
      flag: '--page-size <count>',
      description: 'Results per page, 1-100 CLI cap',
      exposure: 'primary',
      group: 'pagination',
      reason: 'Controls response size; docs say unlimited, so CLI caps interactive requests at 100.',
      valueType: 'integer',
      defaultValue: '100',
    },
  ],
  paramsSchema: tagsParamsSchema,
  execute: params => listWaifuImTags(params),
  normalizeParams: params => tagsParamsSchema.parse(params),
  resultKind: 'waifuim.tags',
  defaultFormat: 'text',
}

export const waifuImProvider: PublicApiProviderModule = {
  manifest: {
    id: 'waifuim',
    name: 'Waifu.im',
    description: 'No-auth HTTPS JSON API for anime image browsing and tag discovery.',
    publicApisCategory: 'Anime',
    homepageUrl: 'https://waifu.im',
    docsUrl: 'https://waifu.im/docs',
    auth: {
      mode: 'none',
      notes: ['OpenAPI public /images and /tags endpoints require no API key or account.'],
    },
    tags: ['anime', 'images', 'tags', 'no-auth'],
    freePlanNotes: [
      'OpenAPI documents PageSize max as unlimited; CLI caps default interactive requests at 100.',
      'OpenAPI documents /images default IsNsfw=False; CLI preserves safe default.',
    ],
  },
  operations: [imagesOperation, tagsOperation],
  endpoints: [
    {
      id: 'waifuim-images',
      method: 'GET',
      urlPattern: 'https://api.waifu.im/images*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Waifu.im image search and browse endpoint returning paginated image metadata.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://api.waifu.im/openapi/v1.json'],
      consumedBy: ['waifuim images'],
      notes: ['No authentication required.', 'PageSize max is documented as unlimited; CLI caps at 100.'],
    },
    {
      id: 'waifuim-tags',
      method: 'GET',
      urlPattern: 'https://api.waifu.im/tags*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Waifu.im tags endpoint returning paginated tag metadata.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://api.waifu.im/openapi/v1.json'],
      consumedBy: ['waifuim tags'],
      notes: ['No authentication required.'],
    },
  ],
}
