import { z } from 'zod'
import {
  listWizardWorldCatalog,
  normalizeWizardWorldCatalogInput,
  WIZARD_WORLD_DEFAULT_LIMIT,
  WIZARD_WORLD_DEFAULT_RESOURCE,
  WIZARD_WORLD_MAX_LIMIT,
  WIZARD_WORLD_MAX_OFFSET,
  type WizardWorldCatalogInput,
} from '../../application/usecases/wizardWorld.js'
import {
  WIZARD_WORLD_ELIXIR_DIFFICULTIES,
  WIZARD_WORLD_RESOURCES,
  WIZARD_WORLD_SPELL_TYPES,
} from '../../infrastructure/openApis/wizardWorldClient.js'
import type {
  PublicApiOperationDefinition,
  PublicApiProviderModule,
} from '../providerTypes.js'

const catalogParamsSchema = z.object({
  resource: z.string().optional(),
  name: z.string().optional(),
  search: z.string().optional(),
  difficulty: z.string().optional(),
  ingredient: z.string().optional(),
  inventor: z.string().optional(),
  manufacturer: z.string().optional(),
  spellType: z.string().optional(),
  incantation: z.string().optional(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
}) satisfies z.ZodType<WizardWorldCatalogInput>

const catalogOperation: PublicApiOperationDefinition<WizardWorldCatalogInput> = {
  id: 'wizardworld.catalog',
  providerId: 'wizardworld',
  name: 'Wizard World catalog',
  commandPath: ['wizardworld', 'catalog'],
  rpcMethod: 'wizardworld.catalog',
  description: 'List bounded Wizard World spells, elixirs, houses, and related data.',
  category: 'books',
  options: [
    {
      name: 'resource',
      flag: '--resource <name>',
      description: [
        `Resource: ${WIZARD_WORLD_RESOURCES.join(', ')},`,
        `default ${WIZARD_WORLD_DEFAULT_RESOURCE}`,
      ].join(' '),
      exposure: 'primary',
      group: 'query',
      reason: 'The official Swagger exposes several read-only JSON collections.',
      valueType: 'string',
      defaultValue: WIZARD_WORLD_DEFAULT_RESOURCE,
    },
    {
      name: 'name',
      flag: '--name <text>',
      description: 'Name filter for elixirs, ingredients, and spells.',
      exposure: 'primary',
      group: 'filters',
      reason: 'Maps to documented Name query parameters on supported resources.',
      valueType: 'string',
    },
    {
      name: 'search',
      flag: '--search <text>',
      description: 'Local case-insensitive search across projected fields.',
      exposure: 'primary',
      group: 'filters',
      reason: 'Provides bounded filtering for resources without documented filters.',
      valueType: 'string',
    },
    {
      name: 'difficulty',
      flag: '--difficulty <name>',
      description: `Elixir difficulty: ${WIZARD_WORLD_ELIXIR_DIFFICULTIES.join(', ')}.`,
      exposure: 'advanced',
      group: 'filters',
      reason: 'Maps to the documented Elixirs Difficulty enum query parameter.',
      valueType: 'string',
    },
    {
      name: 'ingredient',
      flag: '--ingredient <text>',
      description: 'Elixir ingredient name filter.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Maps to the documented Elixirs Ingredient query parameter.',
      valueType: 'string',
    },
    {
      name: 'inventor',
      flag: '--inventor <text>',
      description: 'Elixir inventor full-name filter.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Maps to the documented Elixirs InventorFullName query parameter.',
      valueType: 'string',
    },
    {
      name: 'manufacturer',
      flag: '--manufacturer <text>',
      description: 'Elixir manufacturer filter.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Maps to the documented Elixirs Manufacturer query parameter.',
      valueType: 'string',
    },
    {
      name: 'spellType',
      flag: '--spell-type <name>',
      description: `Spell type: ${WIZARD_WORLD_SPELL_TYPES.join(', ')}.`,
      exposure: 'advanced',
      group: 'filters',
      reason: 'Maps to the documented Spells Type enum query parameter.',
      valueType: 'string',
    },
    {
      name: 'incantation',
      flag: '--incantation <text>',
      description: 'Spell incantation filter.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Maps to the documented Spells Incantation query parameter.',
      valueType: 'string',
    },
    {
      name: 'firstName',
      flag: '--first-name <text>',
      description: 'Wizard first-name filter.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Maps to the documented Wizards FirstName query parameter.',
      valueType: 'string',
    },
    {
      name: 'lastName',
      flag: '--last-name <text>',
      description: 'Wizard last-name filter.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Maps to the documented Wizards LastName query parameter.',
      valueType: 'string',
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: [
        `Rows to show, 1-${String(WIZARD_WORLD_MAX_LIMIT)},`,
        `default ${String(WIZARD_WORLD_DEFAULT_LIMIT)}.`,
      ].join(' '),
      exposure: 'primary',
      group: 'pagination',
      reason: 'Caps terminal output and persisted cache payloads.',
      valueType: 'integer',
      defaultValue: String(WIZARD_WORLD_DEFAULT_LIMIT),
    },
    {
      name: 'offset',
      flag: '--offset <count>',
      description: `Rows to skip, 0-${String(WIZARD_WORLD_MAX_OFFSET)}, default 0.`,
      exposure: 'advanced',
      group: 'pagination',
      reason: 'Supports repeatable pagination over locally filtered results.',
      valueType: 'integer',
      defaultValue: '0',
    },
  ],
  paramsSchema: catalogParamsSchema,
  execute: params => listWizardWorldCatalog(params),
  normalizeParams: params => catalogParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeWizardWorldCatalogInput(params),
  resultKind: 'wizardworld.catalog',
  defaultFormat: 'text',
}

export const wizardWorldProvider: PublicApiProviderModule = {
  manifest: {
    id: 'wizardworld',
    name: 'Wizard World',
    description: [
      'No-auth HTTPS JSON catalog for Harry Potter universe spells, elixirs,',
      'houses, ingredients, magical creatures, and wizards.',
    ].join(' '),
    publicApisCategory: 'Books',
    homepageUrl: 'https://wizard-world-api.herokuapp.com/swagger/index.html',
    docsUrl: 'https://wizard-world-api.herokuapp.com/swagger/index.html',
    auth: {
      mode: 'none',
      notes: [
        [
          'The Swagger-documented read-only GET collections return public JSON',
          'without API key, OAuth, cookies, account setup, or browser sessions.',
        ].join(' '),
      ],
    },
    tags: ['books', 'fantasy', 'harry-potter', 'wizard-world', 'no-auth', 'json'],
    freePlanNotes: [
      'No public rate limit is documented in the OpenAPI document.',
      'The mutating POST /Feedback route is excluded from the CLI contract.',
      'The CLI applies local pagination because collection routes are unpaged.',
    ],
  },
  operations: [catalogOperation],
  endpoints: [
    {
      id: 'wizardworld-catalog-resource',
      method: 'GET',
      urlPattern: [
        'regex:^https://wizard-world-api\\.herokuapp\\.com/',
        '(Elixirs|Houses|Ingredients|MagicalCreature|Spells|Wizards)(\\?.*)?$',
      ].join(''),
      category: 'public-apis:books',
      evidenceStatus: 'confirmed',
      observedOn: '2026-05-11',
      description: 'Wizard World Swagger-documented read-only JSON collection.',
      siteIds: ['public-apis-tui'],
      sampleSources: [
        'https://wizard-world-api.herokuapp.com/swagger/index.html',
        'https://wizard-world-api.herokuapp.com/swagger/v1/swagger.json',
        'https://wizard-world-api.herokuapp.com/Spells?Name=Patronus',
        'https://wizard-world-api.herokuapp.com/Elixirs?Name=Felix',
      ],
      consumedBy: ['public-apis apis run wizardworld.catalog'],
      notes: [
        'No authentication required for selected read-only JSON collection routes.',
        'POST /Feedback and arbitrary route proxying are excluded.',
        'CLI validates enum filters locally before making requests.',
      ],
    },
  ],
}

export type { WizardWorldCatalogInput } from '../../application/usecases/wizardWorld.js'
