import { z } from 'zod'
import { listFilterLists } from '../../application/usecases/filterLists.js'
import {
  FILTER_LISTS_DEFAULT_LIMIT,
  FILTER_LISTS_DEFAULT_QUERY,
  normalizeFilterListsInput,
  type FilterListsInput,
} from '../../infrastructure/openApis/filterListsClient.js'
import type { PublicApiOperationDefinition, PublicApiProviderModule } from '../providerTypes.js'

const listsParamsSchema = z.object({
  query: z.string().optional(),
  limit: z.coerce.number().int().optional(),
  tagId: z.coerce.number().int().optional(),
  syntaxId: z.coerce.number().int().optional(),
  languageId: z.coerce.number().int().optional(),
  licenseId: z.coerce.number().int().optional(),
}) satisfies z.ZodType<FilterListsInput>

const listsOperation: PublicApiOperationDefinition<FilterListsInput> = {
  id: 'filterlists.lists',
  providerId: 'filterlists',
  name: 'Filter List Directory Search',
  commandPath: ['filterlists', 'lists'],
  rpcMethod: 'filterlists.lists',
  description: 'Search FilterLists Directory metadata through the no-auth HTTPS JSON API.',
  category: 'security',
  options: [
    {
      name: 'query',
      flag: '--query <text>',
      description: `Local text search across list metadata, default ${FILTER_LISTS_DEFAULT_QUERY}; use * for all metadata rows`,
      exposure: 'primary',
      group: 'query',
      reason: 'The upstream lists endpoint is unpaginated; local text search keeps security-directory output focused and terminal-readable.',
      defaultValue: FILTER_LISTS_DEFAULT_QUERY,
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: `Rows to show after local filtering, default ${FILTER_LISTS_DEFAULT_LIMIT}, cap 100`,
      exposure: 'primary',
      group: 'pagination',
      reason: 'The upstream response is a directory dump; a CLI cap bounds terminal output and persistence payload size.',
      valueType: 'integer',
      defaultValue: String(FILTER_LISTS_DEFAULT_LIMIT),
    },
    {
      name: 'tagId',
      flag: '--tag-id <id>',
      description: 'Filter by upstream FilterLists tag id',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Tag ids are stable API metadata and allow precise filtering without downloading raw filter-list content; restricted NSFW/proxy/gambling/piracy/paywall tag categories are not exposed.',
      valueType: 'integer',
    },
    {
      name: 'syntaxId',
      flag: '--syntax-id <id>',
      description: 'Filter by upstream syntax id',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Syntax ids are useful for finding compatible adblock/firewall list formats while staying metadata-only.',
      valueType: 'integer',
    },
    {
      name: 'languageId',
      flag: '--language-id <id>',
      description: 'Filter by upstream language id',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Language ids narrow catalog metadata for regional list discovery without exposing raw list downloads.',
      valueType: 'integer',
    },
    {
      name: 'licenseId',
      flag: '--license-id <id>',
      description: 'Filter by upstream license id',
      exposure: 'advanced',
      group: 'filters',
      reason: 'License ids help users inspect redistribution constraints before following upstream list projects.',
      valueType: 'integer',
    },
  ],
  paramsSchema: listsParamsSchema,
  execute: params => listFilterLists(params),
  normalizeParams: params => listsParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeFilterListsInput(params),
  resultKind: 'filterlists.lists',
  defaultFormat: 'text',
}

export const filterListsProvider: PublicApiProviderModule = {
  manifest: {
    id: 'filterlists',
    name: 'FilterLists',
    description: 'No-auth catalog metadata for adblocker and firewall filter lists.',
    publicApisCategory: 'Security',
    homepageUrl: 'https://filterlists.com',
    docsUrl: 'https://api.filterlists.com/index.html',
    auth: {
      mode: 'none',
      notes: ['The FilterLists Directory API v1 Swagger UI and JSON endpoints are public HTTPS endpoints and live probes require no API key.'],
    },
    tags: ['security', 'filter-lists', 'adblock', 'firewall', 'catalog', 'metadata', 'no-auth'],
    freePlanNotes: [
      'This provider exposes catalog metadata only and intentionally does not fetch raw filter-list rule files or arbitrary view URLs.',
      'Restricted NSFW, proxy/circumvention, gambling, piracy, and paywall-bypass metadata categories are excluded from visible results.',
      'The upstream /lists endpoint is unpaginated; CLI search/filter options and a 100-row cap bound output and persistence.',
    ],
  },
  operations: [listsOperation],
  endpoints: [
    {
      id: 'filterlists-openapi',
      method: 'GET',
      urlPattern: 'https://api.filterlists.com/v1/openapi.json',
      category: 'public-apis:security',
      evidenceStatus: 'confirmed',
      description: 'Official OpenAPI schema for the FilterLists Directory API v1.',
      observedOn: '2026-05-09',
      sampleSources: ['https://api.filterlists.com/index.html', 'https://api.filterlists.com/v1/openapi.json'],
      consumedBy: [],
      notes: ['Swagger UI references /v1/openapi.json and no authorization scheme was observed.'],
    },
    {
      id: 'filterlists-directory-lists',
      method: 'GET',
      urlPattern: 'https://api.filterlists.com/lists',
      category: 'public-apis:security',
      evidenceStatus: 'confirmed',
      description: 'FilterLists catalog list metadata including license, syntax, language, tag, and maintainer ids.',
      observedOn: '2026-05-09',
      sampleSources: ['https://api.filterlists.com/lists'],
      consumedBy: ['public-apis apis run filterlists.lists'],
      notes: ['No API key observed; returns application/json. CLI consumes metadata ids only, excludes restricted tag categories, and does not download raw filter-list URLs.'],
    },
    {
      id: 'filterlists-directory-lookups',
      method: 'GET',
      urlPattern: 'https://api.filterlists.com/{licenses|syntaxes|languages|tags|maintainers}',
      category: 'public-apis:security',
      evidenceStatus: 'confirmed',
      description: 'FilterLists metadata lookup endpoints used to resolve ids in list records.',
      observedOn: '2026-05-09',
      sampleSources: [
        'https://api.filterlists.com/licenses',
        'https://api.filterlists.com/syntaxes',
        'https://api.filterlists.com/languages',
        'https://api.filterlists.com/tags',
        'https://api.filterlists.com/maintainers',
      ],
      consumedBy: ['public-apis apis run filterlists.lists'],
      notes: ['Maintainer records can include public project contact fields; text output shows maintainer names only.'],
    },
  ],
}
