import { z } from 'zod'
import {
  getDigitalOceanStatusSummary,
  listDigitalOceanStatusIncidents,
  listDigitalOceanStatusMaintenances,
  normalizeDigitalOceanStatusIncidentsInput,
  normalizeDigitalOceanStatusMaintenancesInput,
  normalizeDigitalOceanStatusSummaryInput,
  type DigitalOceanStatusIncidentsInput,
  type DigitalOceanStatusMaintenancesInput,
  type DigitalOceanStatusSummaryInput,
} from '../../application/usecases/digitalOceanStatus.js'
import type { PublicApiOperationDefinition, PublicApiProviderModule } from '../providerTypes.js'

const summaryParamsSchema = z.object({
  componentQuery: z.string().min(1).optional(),
  componentStatus: z.string().min(1).optional(),
  componentLimit: z.number().int().optional(),
}) satisfies z.ZodType<DigitalOceanStatusSummaryInput>

const incidentsParamsSchema = z.object({
  scope: z.enum(['unresolved', 'recent']).optional(),
  limit: z.number().int().optional(),
  includeUpdates: z.boolean().optional(),
}) satisfies z.ZodType<DigitalOceanStatusIncidentsInput>

const maintenancesParamsSchema = z.object({
  scope: z.enum(['upcoming', 'active', 'recent']).optional(),
  limit: z.number().int().optional(),
  includeUpdates: z.boolean().optional(),
}) satisfies z.ZodType<DigitalOceanStatusMaintenancesInput>

const summaryOperation: PublicApiOperationDefinition<DigitalOceanStatusSummaryInput> = {
  id: 'digitaloceanstatus.summary',
  providerId: 'digitalocean-status',
  name: 'Summary',
  commandPath: ['digitaloceanstatus', 'summary'],
  rpcMethod: 'digitaloceanstatus.summary',
  description: 'Show DigitalOcean current Statuspage status, components, incidents, and scheduled maintenance counts.',
  category: 'development',
  options: [
    {
      name: 'componentQuery',
      flag: '--component-query <text>',
      description: 'Filter components by name substring',
      exposure: 'primary',
      group: 'filters',
      reason: 'The summary endpoint can return hundreds of components; name filtering keeps TUI output focused.',
    },
    {
      name: 'componentStatus',
      flag: '--component-status <status>',
      description: 'Filter components by status, e.g. operational',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Status filtering is useful during incidents but secondary to the overall page status.',
    },
    {
      name: 'componentLimit',
      flag: '--component-limit <count>',
      description: 'Components to show, default 50, CLI cap 222',
      exposure: 'primary',
      group: 'pagination',
      reason: 'Statuspage summary is unpaginated; default/cap uses observed component count to maximize one request without unbounded output.',
      valueType: 'integer',
      defaultValue: '50',
    },
  ],
  paramsSchema: summaryParamsSchema,
  execute: params => getDigitalOceanStatusSummary(params),
  normalizeParams: params => summaryParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeDigitalOceanStatusSummaryInput(params),
  resultKind: 'digitaloceanstatus.summary',
  defaultFormat: 'text',
}

const incidentsOperation: PublicApiOperationDefinition<DigitalOceanStatusIncidentsInput> = {
  id: 'digitaloceanstatus.incidents',
  providerId: 'digitalocean-status',
  name: 'Incidents',
  commandPath: ['digitaloceanstatus', 'incidents'],
  rpcMethod: 'digitaloceanstatus.incidents',
  description: 'List DigitalOcean unresolved or recent Statuspage incidents.',
  category: 'development',
  options: [
    {
      name: 'scope',
      flag: '--scope <unresolved|recent>',
      description: 'Incident scope, default unresolved',
      exposure: 'primary',
      group: 'filters',
      reason: 'Statuspage exposes separate unresolved and all/recent incident feeds; scope is the main user decision.',
      defaultValue: 'unresolved',
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: 'Incidents to show, default 50, CLI cap 100',
      exposure: 'primary',
      group: 'pagination',
      reason: 'Incident feeds are unpaginated; a bounded limit keeps output and cache size predictable.',
      valueType: 'integer',
      defaultValue: '50',
    },
    {
      name: 'includeUpdates',
      flag: '--include-updates <true|false>',
      description: 'Include all incident updates in JSON, default false',
      exposure: 'advanced',
      group: 'content',
      reason: 'Full updates can be verbose; default projects latest update while preserving an opt-in for full JSON analysis.',
      valueType: 'boolean',
      defaultValue: 'false',
    },
  ],
  paramsSchema: incidentsParamsSchema,
  execute: params => listDigitalOceanStatusIncidents(params),
  normalizeParams: params => incidentsParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeDigitalOceanStatusIncidentsInput(params),
  resultKind: 'digitaloceanstatus.incidents',
  defaultFormat: 'text',
}

const maintenancesOperation: PublicApiOperationDefinition<DigitalOceanStatusMaintenancesInput> = {
  id: 'digitaloceanstatus.maintenances',
  providerId: 'digitalocean-status',
  name: 'Maintenances',
  commandPath: ['digitaloceanstatus', 'maintenances'],
  rpcMethod: 'digitaloceanstatus.maintenances',
  description: 'List DigitalOcean upcoming, active, or recent scheduled maintenances.',
  category: 'development',
  options: [
    {
      name: 'scope',
      flag: '--scope <upcoming|active|recent>',
      description: 'Maintenance scope, default upcoming',
      exposure: 'primary',
      group: 'filters',
      reason: 'Statuspage exposes separate upcoming, active, and all maintenance feeds; scope is the main user decision.',
      defaultValue: 'upcoming',
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: 'Maintenances to show, default 50, CLI cap 100',
      exposure: 'primary',
      group: 'pagination',
      reason: 'Maintenance feeds are unpaginated; a bounded limit keeps output and cache size predictable.',
      valueType: 'integer',
      defaultValue: '50',
    },
    {
      name: 'includeUpdates',
      flag: '--include-updates <true|false>',
      description: 'Include all maintenance updates in JSON, default false',
      exposure: 'advanced',
      group: 'content',
      reason: 'Full updates can be verbose; default projects latest update while preserving an opt-in for full JSON analysis.',
      valueType: 'boolean',
      defaultValue: 'false',
    },
  ],
  paramsSchema: maintenancesParamsSchema,
  execute: params => listDigitalOceanStatusMaintenances(params),
  normalizeParams: params => maintenancesParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeDigitalOceanStatusMaintenancesInput(params),
  resultKind: 'digitaloceanstatus.maintenances',
  defaultFormat: 'text',
}

export const digitalOceanStatusProvider: PublicApiProviderModule = {
  manifest: {
    id: 'digitalocean-status',
    name: 'DigitalOcean Status',
    description: 'No-auth HTTPS JSON Statuspage API for DigitalOcean service status, incidents, and scheduled maintenance.',
    publicApisCategory: 'Development',
    homepageUrl: 'https://status.digitalocean.com/',
    docsUrl: 'https://status.digitalocean.com/api',
    auth: {
      mode: 'none',
      notes: ['Statuspage API endpoints are public HTTPS JSON and live probes require no API key.'],
    },
    tags: ['development', 'statuspage', 'digitalocean', 'incidents', 'maintenance', 'no-auth', 'json'],
    freePlanNotes: [
      'Rate limits are not documented by the public Statuspage API.',
      'Statuspage responses expose short cache-control TTLs; all provider operations remain cacheable for offline replay.',
      'Summary currently exposes 222 components; CLI defaults to 50 and caps at 222 for component projection.',
    ],
  },
  operations: [summaryOperation, incidentsOperation, maintenancesOperation],
  endpoints: [
    {
      id: 'digitalocean-status-summary',
      method: 'GET',
      urlPattern: 'https://status.digitalocean.com/api/v2/summary.json',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'DigitalOcean Statuspage summary endpoint.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://status.digitalocean.com/api', 'https://status.digitalocean.com/api/v2/summary.json'],
      consumedBy: ['digitaloceanstatus summary'],
      notes: ['No authentication required; no browser clickstream or scraping required.'],
    },
    {
      id: 'digitalocean-status-incidents',
      method: 'GET',
      urlPattern: 'regex:^https://status\\.digitalocean\\.com/api/v2/incidents(?:/unresolved)?\\.json$',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'DigitalOcean Statuspage incidents endpoint.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://status.digitalocean.com/api', 'https://status.digitalocean.com/api/v2/incidents/unresolved.json'],
      consumedBy: ['digitaloceanstatus incidents'],
      notes: ['No authentication required; no browser clickstream or scraping required.'],
    },
    {
      id: 'digitalocean-status-maintenances',
      method: 'GET',
      urlPattern: 'regex:^https://status\\.digitalocean\\.com/api/v2/scheduled-maintenances(?:/(?:upcoming|active))?\\.json$',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'DigitalOcean Statuspage scheduled maintenances endpoint.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://status.digitalocean.com/api', 'https://status.digitalocean.com/api/v2/scheduled-maintenances/upcoming.json'],
      consumedBy: ['digitaloceanstatus maintenances'],
      notes: ['No authentication required; no browser clickstream or scraping required.'],
    },
  ],
}
