import { z } from 'zod'
import {
  getDogCeoRandomImages,
  listDogCeoBreeds,
  listDogCeoSubBreeds,
  type DogCeoBreedInput,
  type DogCeoImagesInput,
} from '../../application/usecases/dogCeo.js'
import type { PublicApiProviderModule } from '../providerTypes.js'

const emptyParamsSchema = z.object({})

const dogCeoImagesParamsSchema = z.object({
  breed: z.string().min(1).optional(),
  subBreed: z.string().min(1).optional(),
  count: z.number().int().optional(),
}) satisfies z.ZodType<DogCeoImagesInput>

const dogCeoSubBreedsParamsSchema = z.object({
  breed: z.string().min(1),
}) satisfies z.ZodType<Pick<DogCeoBreedInput, 'breed'>>

export const dogCeoProvider: PublicApiProviderModule = {
  manifest: {
    id: 'dogceo',
    name: 'Dog CEO',
    description: 'No-auth HTTPS JSON API for dog breed metadata and random dog images.',
    publicApisCategory: 'Animals',
    homepageUrl: 'https://dog.ceo/dog-api/',
    docsUrl: 'https://dog.ceo/dog-api/documentation/',
    auth: {
      mode: 'none',
      notes: ['Public APIs README lists Auth as No; official Dog CEO endpoints require no API key.'],
    },
    tags: ['animals', 'dogs', 'images', 'breeds', 'no-auth'],
    freePlanNotes: ['No documented API key, quota, or maximum random-image count found in the official documentation; CLI caps --count at 50.'],
  },
  operations: [
    {
      id: 'dogceo.breeds',
      providerId: 'dogceo',
      name: 'Dog breeds',
      commandPath: ['dogceo', 'breeds'],
      rpcMethod: 'dogceo.breeds',
      description: 'List all Dog CEO breeds and sub-breeds.',
      category: 'animals',
      options: [],
      paramsSchema: emptyParamsSchema,
      execute: () => listDogCeoBreeds(),
      normalizeParams: () => ({}),
      resultKind: 'dogceo.breeds',
      defaultFormat: 'text',
    },
    {
      id: 'dogceo.images',
      providerId: 'dogceo',
      name: 'Random dog images',
      commandPath: ['dogceo', 'images'],
      rpcMethod: 'dogceo.images',
      description: 'Fetch random Dog CEO image URLs, optionally filtered by breed and sub-breed.',
      category: 'animals',
      options: [
        {
          name: 'breed',
          flag: '--breed <name>',
          description: 'Dog CEO breed slug, e.g. hound',
          exposure: 'primary',
          group: 'filters',
          reason: 'Primary way to request a useful themed dog image instead of a fully random one.',
        },
        {
          name: 'subBreed',
          flag: '--sub-breed <name>',
          description: 'Dog CEO sub-breed slug; requires --breed',
          exposure: 'advanced',
          group: 'filters',
          reason: 'Useful after users inspect dogceo.breeds or dogceo.subbreeds.',
        },
        {
          name: 'count',
          flag: '--count <count>',
          description: 'Number of random image URLs to request, 1-50',
          exposure: 'primary',
          group: 'pagination',
          reason: 'Controls response size and terminal output length.',
          valueType: 'integer',
        },
      ],
      paramsSchema: dogCeoImagesParamsSchema,
      execute: params => getDogCeoRandomImages(params),
      normalizeParams: params => dogCeoImagesParamsSchema.parse(params),
      resultKind: 'dogceo.images',
      defaultFormat: 'text',
    },
    {
      id: 'dogceo.subbreeds',
      providerId: 'dogceo',
      name: 'Dog sub-breeds',
      commandPath: ['dogceo', 'subbreeds'],
      rpcMethod: 'dogceo.subbreeds',
      description: 'List sub-breeds for one Dog CEO breed.',
      category: 'animals',
      options: [
        {
          name: 'breed',
          flag: '--breed <name>',
          description: 'Dog CEO breed slug, e.g. hound',
          exposure: 'primary',
          group: 'filters',
          reason: 'Required path parameter and the primary lookup intent for sub-breeds.',
        },
      ],
      paramsSchema: dogCeoSubBreedsParamsSchema,
      execute: params => listDogCeoSubBreeds(dogCeoSubBreedsParamsSchema.parse(params)),
      normalizeParams: params => dogCeoSubBreedsParamsSchema.parse(params),
      resultKind: 'dogceo.subbreeds',
      defaultFormat: 'text',
    },
  ],
  endpoints: [
    {
      id: 'dogceo-breeds',
      method: 'GET',
      urlPattern: 'https://dog.ceo/api/breeds/list/all',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Dog CEO endpoint returning a JSON map of breeds to sub-breeds.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://dog.ceo/dog-api/documentation/'],
      consumedBy: ['dogceo breeds'],
      notes: ['No authentication required.'],
    },
    {
      id: 'dogceo-random-images',
      method: 'GET',
      urlPattern: 'https://dog.ceo/api/breeds/image/random*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Dog CEO random dog image endpoint, with optional count suffix.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://dog.ceo/dog-api/documentation/random'],
      consumedBy: ['dogceo images'],
      notes: ['No authentication required.'],
    },
    {
      id: 'dogceo-breed-images',
      method: 'GET',
      urlPattern: 'https://dog.ceo/api/breed/*/images/random*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Dog CEO random dog image endpoint filtered by breed or sub-breed.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://dog.ceo/dog-api/documentation/breed', 'https://dog.ceo/dog-api/documentation/sub-breed'],
      consumedBy: ['dogceo images'],
      notes: ['No authentication required.'],
    },
    {
      id: 'dogceo-subbreeds',
      method: 'GET',
      urlPattern: 'https://dog.ceo/api/breed/*/list',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Dog CEO endpoint returning sub-breeds for one breed.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://dog.ceo/dog-api/documentation/sub-breed'],
      consumedBy: ['dogceo subbreeds'],
      notes: ['No authentication required.'],
    },
  ],
}
