import { z } from 'zod'
import { reverseAdresse, searchAdresse, type AdresseReverseInput, type AdresseSearchInput } from '../../application/usecases/adresse.js'
import {
  ADRESSE_DEFAULT_LATITUDE,
  ADRESSE_DEFAULT_LIMIT,
  ADRESSE_DEFAULT_LONGITUDE,
  ADRESSE_DEFAULT_QUERY,
  ADRESSE_MAX_LIMIT,
  normalizeAdresseReverseInput,
  normalizeAdresseSearchInput,
} from '../../infrastructure/openApis/adresseClient.js'
import type { PublicApiOperationDefinition, PublicApiProviderModule } from '../providerTypes.js'

const addressTypeSchema = z.enum(['housenumber', 'street', 'locality', 'municipality'])

const searchParamsSchema = z.object({
  query: z.string().optional(),
  limit: z.coerce.number().int().optional(),
  latitude: z.coerce.number().optional(),
  longitude: z.coerce.number().optional(),
  postcode: z.string().optional(),
  citycode: z.string().optional(),
  type: addressTypeSchema.optional(),
}) satisfies z.ZodType<AdresseSearchInput>

const reverseParamsSchema = z.object({
  latitude: z.coerce.number().optional(),
  longitude: z.coerce.number().optional(),
  limit: z.coerce.number().int().optional(),
  type: addressTypeSchema.optional(),
}) satisfies z.ZodType<AdresseReverseInput>

const searchOperation: PublicApiOperationDefinition<AdresseSearchInput> = {
  id: 'adresse.search',
  providerId: 'adresse',
  name: 'Search addresses',
  commandPath: ['adresse', 'search'],
  rpcMethod: 'adresse.search',
  description: 'Search French addresses with the Géoplateforme geocoding API.',
  category: 'geocoding',
  options: [
    {
      name: 'query',
      flag: '--query <text>',
      description: `Address or place text, default ${ADRESSE_DEFAULT_QUERY}`,
      exposure: 'primary',
      group: 'query',
      reason: 'The upstream search endpoint requires q text and returns ranked GeoJSON candidates.',
      defaultValue: ADRESSE_DEFAULT_QUERY,
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: `Results to return, default ${String(ADRESSE_DEFAULT_LIMIT)}, max ${String(ADRESSE_MAX_LIMIT)}`,
      exposure: 'primary',
      group: 'pagination',
      reason: 'The API accepts 1-50 results; the CLI keeps output bounded and exposes the documented cap.',
      valueType: 'integer',
      defaultValue: String(ADRESSE_DEFAULT_LIMIT),
    },
    {
      name: 'latitude',
      flag: '--latitude <number>',
      description: 'Optional latitude bias; requires --longitude',
      exposure: 'advanced',
      group: 'filters',
      reason: 'The docs support lat/lon to favor nearby candidates; it is optional because text search is primary.',
      valueType: 'string',
    },
    {
      name: 'longitude',
      flag: '--longitude <number>',
      description: 'Optional longitude bias; requires --latitude',
      exposure: 'advanced',
      group: 'filters',
      reason: 'The docs support lon/lat to favor nearby candidates; it is optional because text search is primary.',
      valueType: 'string',
    },
    {
      name: 'postcode',
      flag: '--postcode <code>',
      description: 'Optional 5-digit French postal-code filter',
      exposure: 'advanced',
      group: 'filters',
      reason: 'The docs expose postcode filtering for address results and it is useful for narrowing ambiguous address text.',
    },
    {
      name: 'citycode',
      flag: '--citycode <insee>',
      description: 'Optional INSEE city-code filter, e.g. 75101',
      exposure: 'advanced',
      group: 'filters',
      reason: 'The docs expose citycode filtering for deterministic French commune scoping.',
    },
    {
      name: 'type',
      flag: '--type <housenumber|street|locality|municipality>',
      description: 'Optional address result type filter',
      exposure: 'advanced',
      group: 'filters',
      reason: 'The docs expose address type filtering; only the four documented address values are accepted.',
    },
  ],
  paramsSchema: searchParamsSchema,
  execute: params => searchAdresse(params),
  normalizeParams: params => searchParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeAdresseSearchInput(params),
  resultKind: 'adresse.search',
  defaultFormat: 'text',
}

const reverseOperation: PublicApiOperationDefinition<AdresseReverseInput> = {
  id: 'adresse.reverse',
  providerId: 'adresse',
  name: 'Reverse geocode',
  commandPath: ['adresse', 'reverse'],
  rpcMethod: 'adresse.reverse',
  description: 'Reverse geocode French WGS84 coordinates with the Géoplateforme API.',
  category: 'geocoding',
  options: [
    {
      name: 'latitude',
      flag: '--latitude <number>',
      description: `WGS84 latitude, default ${String(ADRESSE_DEFAULT_LATITUDE)}`,
      exposure: 'primary',
      group: 'query',
      reason: 'The reverse endpoint requires latitude to find nearby address candidates.',
      valueType: 'string',
      defaultValue: String(ADRESSE_DEFAULT_LATITUDE),
    },
    {
      name: 'longitude',
      flag: '--longitude <number>',
      description: `WGS84 longitude, default ${String(ADRESSE_DEFAULT_LONGITUDE)}`,
      exposure: 'primary',
      group: 'query',
      reason: 'The reverse endpoint requires longitude to find nearby address candidates.',
      valueType: 'string',
      defaultValue: String(ADRESSE_DEFAULT_LONGITUDE),
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: `Results to return, default ${String(ADRESSE_DEFAULT_LIMIT)}, max ${String(ADRESSE_MAX_LIMIT)}`,
      exposure: 'primary',
      group: 'pagination',
      reason: 'The API accepts 1-50 results; the CLI keeps output bounded and exposes the documented cap.',
      valueType: 'integer',
      defaultValue: String(ADRESSE_DEFAULT_LIMIT),
    },
    {
      name: 'type',
      flag: '--type <housenumber|street|locality|municipality>',
      description: 'Optional address result type filter',
      exposure: 'advanced',
      group: 'filters',
      reason: 'The docs expose address type filtering; only the four documented address values are accepted.',
    },
  ],
  paramsSchema: reverseParamsSchema,
  execute: params => reverseAdresse(params),
  normalizeParams: params => reverseParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeAdresseReverseInput(params),
  resultKind: 'adresse.reverse',
  defaultFormat: 'text',
}

export const adresseProvider: PublicApiProviderModule = {
  manifest: {
    id: 'adresse',
    name: 'adresse.data.gouv.fr',
    description: 'French public address geocoding and reverse geocoding API now served by data.geopf.fr/geocodage.',
    publicApisCategory: 'Geocoding',
    homepageUrl: 'https://adresse.data.gouv.fr',
    docsUrl: 'https://data.geopf.fr/geocodage/getCapabilities',
    auth: {
      mode: 'none',
      notes: ['The implemented Géoplateforme endpoints return JSON without API keys, OAuth, cookies, browser sessions, or account setup.'],
    },
    tags: ['geocoding', 'france', 'addresses', 'geojson', 'government', 'no-auth'],
    freePlanNotes: [
      'The legacy api-adresse.data.gouv.fr host is deprecated and advertises migration to https://data.geopf.fr/geocodage/.',
      'Live headers show x-ratelimit-limit-second: 1 and ratelimit-limit: 50; CLI commands are bounded to 50 results.',
      'Geocoding and reverse geocoding queries can reveal locations; persistence is opt-in through --persist.',
    ],
  },
  operations: [searchOperation, reverseOperation],
  endpoints: [
    {
      id: 'adresse-geoplateforme-capabilities',
      method: 'GET',
      urlPattern: 'https://data.geopf.fr/geocodage/getCapabilities',
      category: 'public-apis:geocoding',
      evidenceStatus: 'confirmed',
      description: 'Géoplateforme geocoding service metadata and parameter contract.',
      siteIds: ['public-apis-tui'],
      observedOn: '2026-05-08',
      sampleSources: ['https://adresse.data.gouv.fr', 'https://data.geopf.fr/geocodage/getCapabilities'],
      consumedBy: ['public-apis apis info adresse'],
      notes: ['No authentication required.', 'Response is JSON and documents search/reverse operations plus rate-limit headers observed in live probes.'],
    },
    {
      id: 'adresse-geoplateforme-search',
      method: 'GET',
      urlPattern: 'https://data.geopf.fr/geocodage/search',
      category: 'public-apis:geocoding',
      evidenceStatus: 'confirmed',
      description: 'Géoplateforme address text geocoding endpoint returning GeoJSON FeatureCollection JSON.',
      siteIds: ['public-apis-tui'],
      observedOn: '2026-05-08',
      sampleSources: ['https://data.geopf.fr/geocodage/search?q=8%20bd%20du%20port&limit=2'],
      consumedBy: ['public-apis apis run adresse.search'],
      notes: ['No authentication required.', 'The q parameter is required upstream; limit must be an integer from 1 to 50.', 'Legacy api-adresse.data.gouv.fr host is deprecated and is not consumed.'],
    },
    {
      id: 'adresse-geoplateforme-reverse',
      method: 'GET',
      urlPattern: 'https://data.geopf.fr/geocodage/reverse',
      category: 'public-apis:geocoding',
      evidenceStatus: 'confirmed',
      description: 'Géoplateforme reverse geocoding endpoint returning nearby address GeoJSON FeatureCollection JSON.',
      siteIds: ['public-apis-tui'],
      observedOn: '2026-05-08',
      sampleSources: ['https://data.geopf.fr/geocodage/reverse?lon=2.37&lat=48.357&limit=2'],
      consumedBy: ['public-apis apis run adresse.reverse'],
      notes: ['No authentication required.', 'The lat/lon parameters select the coordinate and limit must be 1 to 50.', 'Only JSON GeoJSON results are consumed; no browser clickstream or scraping is used.'],
    },
  ],
}

export type { AdresseReverseInput, AdresseSearchInput } from '../../application/usecases/adresse.js'
