import { z } from 'zod'
import { listGNewsHeadlines, searchGNews } from '../../application/usecases/gnews.js'
import {
  GNEWS_DEFAULT_CATEGORY,
  GNEWS_DEFAULT_MAX,
  GNEWS_DEFAULT_PAGE,
  GNEWS_DEFAULT_SEARCH_QUERY,
  GNEWS_ENV_API_KEY,
  normalizeGNewsHeadlinesInput,
  normalizeGNewsSearchInput,
  type GNewsHeadlinesInput,
  type GNewsSearchInput,
} from '../../infrastructure/openApis/gnewsClient.js'
import type { PublicApiOperationDefinition, PublicApiProviderModule } from '../providerTypes.js'

const searchParamsSchema = z.object({
  apiKey: z.string().min(1).optional(),
  query: z.string().min(1).optional(),
  language: z.string().min(1).optional(),
  country: z.string().min(1).optional(),
  max: z.coerce.number().optional(),
  searchIn: z.string().min(1).optional(),
  nullable: z.string().min(1).optional(),
  from: z.string().min(1).optional(),
  to: z.string().min(1).optional(),
  sortBy: z.enum(['publishedAt', 'relevance']).optional(),
  page: z.coerce.number().optional(),
  expand: z.string().min(1).optional(),
}) satisfies z.ZodType<GNewsSearchInput>

const headlinesParamsSchema = z.object({
  apiKey: z.string().min(1).optional(),
  category: z.enum(['general', 'world', 'nation', 'business', 'technology', 'entertainment', 'sports', 'science', 'health']).optional(),
  query: z.string().min(1).optional(),
  language: z.string().min(1).optional(),
  country: z.string().min(1).optional(),
  max: z.coerce.number().optional(),
  nullable: z.string().min(1).optional(),
  from: z.string().min(1).optional(),
  to: z.string().min(1).optional(),
  page: z.coerce.number().optional(),
  expand: z.string().min(1).optional(),
}) satisfies z.ZodType<GNewsHeadlinesInput>

const searchOperation: PublicApiOperationDefinition<GNewsSearchInput> = {
  id: 'gnews.search',
  providerId: 'gnews',
  name: 'Search',
  commandPath: ['gnews', 'search'],
  rpcMethod: 'gnews.search',
  description: 'Search GNews articles through the documented keyed REST API.',
  category: 'news',
  options: [
    { name: 'apiKey', flag: '--api-key <key>', description: `GNews API key; defaults to ${GNEWS_ENV_API_KEY} or local config`, exposure: 'advanced', group: 'authentication', reason: 'Exposed only for one-off smoke tests; local provider config or env is preferred.' },
    { name: 'query', flag: '--query <text>', description: `Search query, default "${GNEWS_DEFAULT_SEARCH_QUERY}"`, exposure: 'primary', group: 'query', reason: 'Primary search intent for article discovery.', defaultValue: GNEWS_DEFAULT_SEARCH_QUERY },
    { name: 'language', flag: '--language <code>', description: 'Two-letter language code filter', exposure: 'primary', group: 'filters', reason: 'Language materially affects readable terminal results.' },
    { name: 'country', flag: '--country <code>', description: 'Two-letter country code filter', exposure: 'primary', group: 'filters', reason: 'Country is a common news localization filter.' },
    { name: 'searchIn', flag: '--search-in <fields>', description: 'Comma-separated fields: title, description, content', exposure: 'advanced', group: 'filters', reason: 'Useful for precision searches without exposing arbitrary raw parameters.' },
    { name: 'from', flag: '--from <iso8601>', description: 'Start datetime filter', exposure: 'advanced', group: 'filters', reason: 'Date range is useful but easy to misuse, so advanced.' },
    { name: 'to', flag: '--to <iso8601>', description: 'End datetime filter', exposure: 'advanced', group: 'filters', reason: 'Pairs with --from for bounded historical searches.' },
    { name: 'sortBy', flag: '--sort-by <publishedAt|relevance>', description: 'Sort order', exposure: 'advanced', group: 'presentation', reason: 'Search sorting affects result order but is secondary to query/filter UX.', defaultValue: 'publishedAt' },
    { name: 'nullable', flag: '--nullable <fields>', description: 'Allow nullable fields: description, content, image', exposure: 'advanced', group: 'content', reason: 'Advanced content completeness control from GNews docs.' },
    { name: 'expand', flag: '--expand <content>', description: 'Request full content expansion when provider plan supports it', exposure: 'hidden', group: 'content', reason: 'GNews documents expand=content as plan-dependent; hide from default CLI UX to protect free-key users and cache size.' },
    { name: 'max', flag: '--max <count>', description: `Articles per page, default/cap ${GNEWS_DEFAULT_MAX}`, exposure: 'primary', group: 'pagination', reason: 'Docs list max=100; defaulting to the maximum maximizes one request.', valueType: 'integer', defaultValue: String(GNEWS_DEFAULT_MAX) },
    { name: 'page', flag: '--page <number>', description: `Page number, default ${GNEWS_DEFAULT_PAGE}`, exposure: 'advanced', group: 'pagination', reason: 'Needed for continuation within the documented 1000-article window.', valueType: 'integer', defaultValue: String(GNEWS_DEFAULT_PAGE) },
  ],
  paramsSchema: searchParamsSchema,
  execute: params => searchGNews(params),
  normalizeParams: params => searchParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeGNewsSearchInput(params),
  resultKind: 'gnews.search',
  defaultFormat: 'text',
}

const headlinesOperation: PublicApiOperationDefinition<GNewsHeadlinesInput> = {
  id: 'gnews.headlines',
  providerId: 'gnews',
  name: 'Top Headlines',
  commandPath: ['gnews', 'headlines'],
  rpcMethod: 'gnews.headlines',
  description: 'Fetch GNews top headlines through the documented keyed REST API.',
  category: 'news',
  options: [
    { name: 'apiKey', flag: '--api-key <key>', description: `GNews API key; defaults to ${GNEWS_ENV_API_KEY} or local config`, exposure: 'advanced', group: 'authentication', reason: 'Exposed only for one-off smoke tests; local provider config or env is preferred.' },
    { name: 'category', flag: '--category <name>', description: `Headline category, default ${GNEWS_DEFAULT_CATEGORY}`, exposure: 'primary', group: 'filters', reason: 'Category is the main top-headlines browsing dimension.', defaultValue: GNEWS_DEFAULT_CATEGORY },
    { name: 'query', flag: '--query <text>', description: 'Optional keyword filter inside top headlines', exposure: 'primary', group: 'query', reason: 'Allows targeted top-headline browsing without switching operation.' },
    { name: 'language', flag: '--language <code>', description: 'Two-letter language code filter', exposure: 'primary', group: 'filters', reason: 'Language materially affects readable terminal results.' },
    { name: 'country', flag: '--country <code>', description: 'Two-letter country code filter', exposure: 'primary', group: 'filters', reason: 'Country is a common news localization filter.' },
    { name: 'from', flag: '--from <iso8601>', description: 'Start datetime filter', exposure: 'advanced', group: 'filters', reason: 'Date range is useful but secondary to headline browsing.' },
    { name: 'to', flag: '--to <iso8601>', description: 'End datetime filter', exposure: 'advanced', group: 'filters', reason: 'Pairs with --from for bounded headline windows.' },
    { name: 'nullable', flag: '--nullable <fields>', description: 'Allow nullable fields: description, content, image', exposure: 'advanced', group: 'content', reason: 'Advanced content completeness control from GNews docs.' },
    { name: 'expand', flag: '--expand <content>', description: 'Request full content expansion when provider plan supports it', exposure: 'hidden', group: 'content', reason: 'GNews documents expand=content as plan-dependent; hide from default CLI UX to protect free-key users and cache size.' },
    { name: 'max', flag: '--max <count>', description: `Articles per page, default/cap ${GNEWS_DEFAULT_MAX}`, exposure: 'primary', group: 'pagination', reason: 'Docs list max=100; defaulting to the maximum maximizes one request.', valueType: 'integer', defaultValue: String(GNEWS_DEFAULT_MAX) },
    { name: 'page', flag: '--page <number>', description: `Page number, default ${GNEWS_DEFAULT_PAGE}`, exposure: 'advanced', group: 'pagination', reason: 'Needed for continuation within the documented 1000-article window.', valueType: 'integer', defaultValue: String(GNEWS_DEFAULT_PAGE) },
  ],
  paramsSchema: headlinesParamsSchema,
  execute: params => listGNewsHeadlines(params),
  normalizeParams: params => headlinesParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeGNewsHeadlinesInput(params),
  resultKind: 'gnews.headlines',
  defaultFormat: 'text',
}

export const gnewsProvider: PublicApiProviderModule = {
  manifest: {
    id: 'gnews',
    name: 'GNews',
    description: 'Keyed REST API for news search and Google News-ranked top headlines.',
    publicApisCategory: 'News',
    homepageUrl: 'https://gnews.io/',
    docsUrl: 'https://docs.gnews.io/',
    auth: {
      mode: 'api-key',
      envVars: [GNEWS_ENV_API_KEY],
      notes: ['Uses apikey query authentication; store secrets only in environment or local provider config.'],
    },
    tags: ['news', 'headlines', 'media', 'keyed'],
    freePlanNotes: ['Docs list max=100 and article windows capped at 1000; default max uses 100 to conserve requests.'],
  },
  operations: [searchOperation, headlinesOperation],
  endpoints: [
    {
      id: 'gnews-search',
      method: 'GET',
      urlPattern: 'https://gnews.io/api/v4/search',
      category: 'public-api:news',
      evidenceStatus: 'confirmed',
      observedOn: '2026-05-04',
      sampleSources: ['https://docs.gnews.io/', 'https://gnews.io/api/v4/search?q=Google&lang=en&max=5'],
      consumedBy: ['gnews.search'],
      description: 'GNews article search endpoint with apikey query authentication.',
      notes: ['Requires API key; cache keys must omit apikey.'],
    },
    {
      id: 'gnews-top-headlines',
      method: 'GET',
      urlPattern: 'https://gnews.io/api/v4/top-headlines',
      category: 'public-api:news',
      evidenceStatus: 'confirmed',
      observedOn: '2026-05-04',
      sampleSources: ['https://docs.gnews.io/'],
      consumedBy: ['gnews.headlines'],
      description: 'GNews top headlines endpoint with apikey query authentication.',
      notes: ['Requires API key; cache keys must omit apikey.'],
    },
  ],
}
