import { z } from 'zod'
import {
  convertHebcalDate,
  listHebcalCalendar,
  normalizeHebcalCalendarInput,
  normalizeHebcalConvertInput,
  type HebcalCalendarInput,
  type HebcalConvertInput,
} from '../../application/usecases/hebcal.js'
import type { PublicApiOperationDefinition, PublicApiProviderModule } from '../providerTypes.js'

const convertParamsSchema = z.object({
  date: z.string().min(1).optional(),
  strict: z.boolean().optional(),
}) satisfies z.ZodType<HebcalConvertInput>

const calendarParamsSchema = z.object({
  start: z.string().min(1).optional(),
  end: z.string().min(1).optional(),
  days: z.number().int().optional(),
  israel: z.boolean().optional(),
  major: z.boolean().optional(),
  minor: z.boolean().optional(),
  roshChodesh: z.boolean().optional(),
  modern: z.boolean().optional(),
  shabbat: z.boolean().optional(),
}) satisfies z.ZodType<HebcalCalendarInput>

const convertOperation: PublicApiOperationDefinition<HebcalConvertInput> = {
  id: 'hebcal.convert',
  providerId: 'hebcal',
  name: 'Convert Hebrew Date',
  commandPath: ['hebcal', 'convert'],
  rpcMethod: 'hebcal.convert',
  description: 'Convert a Gregorian date to a Hebrew date using Hebcal no-auth JSON API.',
  category: 'calendar',
  options: [
    {
      name: 'date',
      flag: '--date <YYYY-MM-DD>',
      description: 'Gregorian date to convert, default today',
      exposure: 'primary',
      group: 'query',
      reason: 'The converter endpoint is date-addressed and date lookup is the primary terminal workflow.',
    },
    {
      name: 'strict',
      flag: '--strict <true|false>',
      description: 'Reject invalid dates, default true',
      exposure: 'advanced',
      group: 'query',
      reason: 'The documented strict flag controls converter validation but most users should keep the safe default.',
      valueType: 'boolean',
      defaultValue: 'true',
    },
  ],
  paramsSchema: convertParamsSchema,
  execute: params => convertHebcalDate(params),
  normalizeParams: params => normalizeHebcalConvertInput(convertParamsSchema.parse(params)),
  createCacheKeyParams: params => normalizeHebcalConvertInput(params),
  resultKind: 'hebcal.convert',
  defaultFormat: 'text',
}

const calendarOperation: PublicApiOperationDefinition<HebcalCalendarInput> = {
  id: 'hebcal.calendar',
  providerId: 'hebcal',
  name: 'Jewish Calendar',
  commandPath: ['hebcal', 'calendar'],
  rpcMethod: 'hebcal.calendar',
  description: 'List Jewish calendar events from Hebcal over a bounded date range.',
  category: 'calendar',
  options: [
    {
      name: 'start',
      flag: '--start <YYYY-MM-DD>',
      description: 'Range start date, default today',
      exposure: 'primary',
      group: 'query',
      reason: 'The documented calendar API supports start/end range requests and start anchors the terminal view.',
    },
    {
      name: 'end',
      flag: '--end <YYYY-MM-DD>',
      description: 'Range end date; overrides --days when provided',
      exposure: 'advanced',
      group: 'query',
      reason: 'End date is useful for exact ranges but days is a simpler primary CLI control.',
    },
    {
      name: 'days',
      flag: '--days <count>',
      description: 'Days to request when --end is omitted, default 7, CLI cap 180',
      exposure: 'primary',
      group: 'pagination',
      reason: 'Hebcal documents 180-day truncation for date-range style requests; CLI enforces that cap to keep cache/output bounded.',
      valueType: 'integer',
      defaultValue: '7',
    },
    {
      name: 'israel',
      flag: '--israel <true|false>',
      description: 'Use Israel holiday schedule, default false',
      exposure: 'primary',
      group: 'filters',
      reason: 'The documented i flag materially changes holiday output and is understandable in terminal UX.',
      valueType: 'boolean',
      defaultValue: 'false',
    },
    {
      name: 'major',
      flag: '--major <true|false>',
      description: 'Include major holidays, default true',
      exposure: 'advanced',
      group: 'filters',
      reason: 'The documented maj flag is useful but default inclusion keeps the common workflow simple.',
      valueType: 'boolean',
      defaultValue: 'true',
    },
    {
      name: 'minor',
      flag: '--minor <true|false>',
      description: 'Include minor holidays, default true',
      exposure: 'advanced',
      group: 'filters',
      reason: 'The documented min flag is a secondary calendar filter.',
      valueType: 'boolean',
      defaultValue: 'true',
    },
    {
      name: 'roshChodesh',
      flag: '--rosh-chodesh <true|false>',
      description: 'Include Rosh Chodesh events, default true',
      exposure: 'advanced',
      group: 'filters',
      reason: 'The documented nx flag is exposed with a readable name for calendar specialists.',
      valueType: 'boolean',
      defaultValue: 'true',
    },
    {
      name: 'modern',
      flag: '--modern <true|false>',
      description: 'Include modern holidays, default true',
      exposure: 'advanced',
      group: 'filters',
      reason: 'The documented mod flag is useful but less central than date range and Israel schedule.',
      valueType: 'boolean',
      defaultValue: 'true',
    },
    {
      name: 'shabbat',
      flag: '--shabbat <true|false>',
      description: 'Include Shabbat events, default true',
      exposure: 'advanced',
      group: 'filters',
      reason: 'The documented s flag can add weekly events; expose it for output tuning without surfacing every raw Hebcal parameter.',
      valueType: 'boolean',
      defaultValue: 'true',
    },
  ],
  paramsSchema: calendarParamsSchema,
  execute: params => listHebcalCalendar(params),
  normalizeParams: params => normalizeHebcalCalendarInput(calendarParamsSchema.parse(params)),
  createCacheKeyParams: params => normalizeHebcalCalendarInput(params),
  resultKind: 'hebcal.calendar',
  defaultFormat: 'text',
}

export const hebcalProvider: PublicApiProviderModule = {
  manifest: {
    id: 'hebcal',
    name: 'Hebcal',
    description: 'No-auth HTTPS JSON APIs for Hebrew date conversion and Jewish calendar events.',
    publicApisCategory: 'Calendar',
    homepageUrl: 'https://www.hebcal.com/',
    docsUrl: 'https://www.hebcal.com/home/developer-apis',
    auth: {
      mode: 'none',
      notes: ['Hebcal developer API docs state that no registration or API keys are required.'],
    },
    tags: ['calendar', 'hebrew-calendar', 'holidays', 'no-auth', 'json'],
    freePlanNotes: [
      'Docs state clients making more than 90 requests per 10-second window may be throttled or blocked.',
      'Calendar range defaults to 7 days and caps at the documented 180-day truncation boundary.',
    ],
  },
  operations: [convertOperation, calendarOperation],
  endpoints: [
    {
      id: 'hebcal-converter',
      method: 'GET',
      urlPattern: 'https://www.hebcal.com/converter',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Hebcal Gregorian-to-Hebrew date converter JSON endpoint.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://www.hebcal.com/home/219/hebrew-date-converter-rest-api'],
      consumedBy: ['hebcal convert'],
      notes: ['No authentication required.'],
    },
    {
      id: 'hebcal-calendar',
      method: 'GET',
      urlPattern: 'https://www.hebcal.com/hebcal',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Hebcal Jewish calendar JSON endpoint for date ranges and event flags.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://www.hebcal.com/home/195/jewish-calendar-rest-api'],
      consumedBy: ['hebcal calendar'],
      notes: ['No authentication required; CLI caps range at 180 days.'],
    },
  ],
}
