import { z } from 'zod'
import { MEDIASTACK_ENV_API_KEY } from './client.js'
import { listMediastackNews, type MediastackNewsInput } from './news.js'
import type { PublicApiProviderModule } from '../providerTypes.js'

const mediastackNewsParamsSchema = z.object({
  apiKey: z.string().min(1).optional(),
  keywords: z.string().min(1).optional(),
  sources: z.string().min(1).optional(),
  categories: z.string().min(1).optional(),
  countries: z.string().min(1).optional(),
  languages: z.string().min(1).optional(),
  date: z.string().min(1).optional(),
  sort: z.enum(['published_desc', 'published_asc', 'popularity']).optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
}) satisfies z.ZodType<MediastackNewsInput>

export const mediastackProvider: PublicApiProviderModule = {
  manifest: {
    id: 'mediastack',
    name: 'Mediastack',
    description: 'News API for current and historical headlines from global sources.',
    publicApisCategory: 'News',
    homepageUrl: 'https://mediastack.com/',
    docsUrl: 'https://mediastack.com/documentation',
    auth: {
      mode: 'api-key',
      envVars: [MEDIASTACK_ENV_API_KEY],
      notes: ['Uses access_key query authentication.'],
    },
    tags: ['news', 'media', 'headlines', 'free-plan'],
    freePlanNotes: ['Live news can be delayed on the free plan.'],
  },
  operations: [
    {
      id: 'mediastack.news',
      providerId: 'mediastack',
      name: 'News',
      commandPath: ['mediastack', 'news'],
      rpcMethod: 'mediastack.news',
      description: 'Fetch Mediastack live news through the documented REST API.',
      category: 'news',
      options: [
        {
          name: 'apiKey',
          flag: '--api-key <key>',
          description: 'Mediastack access key; defaults to MEDIASTACK_API_KEY',
          exposure: 'advanced',
          group: 'authentication',
          reason: 'Exposed for one-off smoke tests; persisted local provider config is preferred for normal use.',
        },
        {
          name: 'keywords',
          flag: '--keywords <text>',
          description: 'Search keywords, e.g. "technology"',
          exposure: 'primary',
          group: 'query',
          reason: 'Primary intent field for interactive headline search.',
        },
        {
          name: 'sources',
          flag: '--sources <ids>',
          description: 'Comma-separated source ids to include or exclude with -source',
          exposure: 'advanced',
          group: 'filters',
          reason: 'Useful for precise source filtering after users discover source identifiers.',
        },
        {
          name: 'categories',
          flag: '--categories <ids>',
          description: 'Comma-separated categories, e.g. business,technology',
          exposure: 'primary',
          group: 'filters',
          reason: 'High-value domain filter with a small documented vocabulary.',
        },
        {
          name: 'countries',
          flag: '--countries <codes>',
          description: 'Comma-separated country codes, e.g. us,gb',
          exposure: 'primary',
          group: 'filters',
          reason: 'Common news localization filter that materially changes results.',
        },
        {
          name: 'languages',
          flag: '--languages <codes>',
          description: 'Comma-separated language codes, e.g. en,de',
          exposure: 'primary',
          group: 'filters',
          reason: 'Common news localization filter that materially changes readability.',
        },
        {
          name: 'date',
          flag: '--date <date>',
          description: 'Date filter accepted by Mediastack, e.g. YYYY-MM-DD',
          exposure: 'advanced',
          group: 'filters',
          reason: 'Useful for historical lookup but requires provider-specific date syntax knowledge.',
        },
        {
          name: 'sort',
          flag: '--sort <sort>',
          description: 'Sort: published_desc, published_asc, or popularity',
          exposure: 'advanced',
          group: 'presentation',
          reason: 'Useful result-order control, but default is sensible for headline browsing.',
          defaultValue: 'published_desc',
        },
        {
          name: 'limit',
          flag: '--limit <count>',
          description: 'Number of articles to fetch, 1-100',
          exposure: 'primary',
          group: 'pagination',
          reason: 'Controls quota usage and output length; default follows the documented maximum.',
          valueType: 'integer',
          defaultValue: '100',
        },
        {
          name: 'offset',
          flag: '--offset <count>',
          description: 'Pagination offset, 0 or greater',
          exposure: 'advanced',
          group: 'pagination',
          reason: 'Needed for replaying or continuing result pages without adding a separate pager UI.',
          valueType: 'integer',
        },
      ],
      paramsSchema: mediastackNewsParamsSchema,
      execute: params => listMediastackNews(params),
      normalizeParams: params => mediastackNewsParamsSchema.parse(params),
      createCacheKeyParams: ({ apiKey: _apiKey, ...params }) => params,
      resultKind: 'mediastack.news',
      defaultFormat: 'text',
    },
  ],
  endpoints: [
    {
      id: 'mediastack-news',
      method: 'GET',
      urlPattern: 'https://api.mediastack.com/v1/news*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Mediastack live news endpoint used as the first public-apis CLI TUI integration.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://mediastack.com/documentation'],
      consumedBy: ['mediastack news'],
      notes: [
        'Uses access_key query authentication from MEDIASTACK_API_KEY or --api-key.',
        'This project calls the documented REST API directly and does not use Chrome clickstream data.',
      ],
    },
    {
      id: 'mediastack-sources',
      method: 'GET',
      urlPattern: 'https://api.mediastack.com/v1/sources*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Mediastack source metadata endpoint documented for future filters and discovery flows.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://mediastack.com/documentation'],
      notes: ['Documented but not yet consumed by the initial TUI command.'],
    },
  ],
}
