import { z } from 'zod'
import { renderQuickChart, type QuickChartRenderInput } from '../../application/usecases/quickChart.js'
import { normalizeQuickChartRenderInput } from '../../infrastructure/openApis/quickChartClient.js'
import type { PublicApiOperationDefinition, PublicApiProviderModule } from '../providerTypes.js'

const renderParamsSchema = z.object({
  chartType: z.string().optional(),
  labels: z.string().optional(),
  data: z.string().optional(),
  title: z.string().optional(),
  width: z.number().int().optional(),
  height: z.number().int().optional(),
  format: z.string().optional(),
  backgroundColor: z.string().optional(),
  devicePixelRatio: z.number().optional(),
}) satisfies z.ZodType<QuickChartRenderInput>

const renderOperation: PublicApiOperationDefinition<QuickChartRenderInput> = {
  id: 'quickchart.render',
  providerId: 'quickchart',
  name: 'Render Chart',
  commandPath: ['quickchart', 'render'],
  rpcMethod: 'quickchart.render',
  description: 'Render a simple chart image through QuickChart no-auth HTTPS API.',
  category: 'development',
  options: [
    {
      name: 'chartType',
      flag: '--type <bar|line|pie|doughnut>',
      description: 'Chart.js chart type, default bar',
      exposure: 'primary',
      group: 'content',
      reason: 'Chart type is the primary user-facing decision for generated chart output.',
      defaultValue: 'bar',
    },
    {
      name: 'labels',
      flag: '--labels <csv>',
      description: 'Comma-separated labels, default A,B,C',
      exposure: 'primary',
      group: 'content',
      reason: 'Labels are the primary data dimension for a simple chart builder UX.',
      defaultValue: 'A,B,C',
    },
    {
      name: 'data',
      flag: '--data <csv>',
      description: 'Comma-separated numbers, default 3,7,4',
      exposure: 'primary',
      group: 'content',
      reason: 'Data values are the primary metric dimension for a simple chart builder UX.',
      defaultValue: '3,7,4',
    },
    {
      name: 'title',
      flag: '--title <text>',
      description: 'Chart title, default Public APIs',
      exposure: 'primary',
      group: 'content',
      reason: 'The title materially changes the generated artifact and makes TUI previews understandable.',
      defaultValue: 'Public APIs',
    },
    {
      name: 'width',
      flag: '--width <pixels>',
      description: 'Image width, default 500, max 2000',
      exposure: 'primary',
      group: 'presentation',
      reason: 'QuickChart documents image dimensions and they materially affect generated output.',
      valueType: 'integer',
      defaultValue: '500',
    },
    {
      name: 'height',
      flag: '--height <pixels>',
      description: 'Image height, default 300, max 2000',
      exposure: 'primary',
      group: 'presentation',
      reason: 'QuickChart documents image dimensions and they materially affect generated output.',
      valueType: 'integer',
      defaultValue: '300',
    },
    {
      name: 'format',
      flag: '--format-image <png|svg|webp|pdf>',
      description: 'Rendered artifact format, default png',
      exposure: 'primary',
      group: 'presentation',
      reason: 'Output media type changes the persisted artifact and downstream terminal workflow.',
      defaultValue: 'png',
    },
    {
      name: 'backgroundColor',
      flag: '--background-color <css>',
      description: 'Background color such as transparent or #ffffff',
      exposure: 'advanced',
      group: 'presentation',
      reason: 'Useful visual tuning, but secondary to data, dimensions, and format.',
      defaultValue: undefined,
    },
    {
      name: 'devicePixelRatio',
      flag: '--device-pixel-ratio <ratio>',
      description: 'Device pixel ratio, 1-4',
      exposure: 'advanced',
      group: 'presentation',
      reason: 'High-DPI tuning is useful for export quality but not needed for default CLI exploration.',
      valueType: 'integer',
      defaultValue: undefined,
    },
  ],
  paramsSchema: renderParamsSchema,
  execute: params => renderQuickChart(params),
  normalizeParams: params => renderParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeQuickChartRenderInput(params),
  resultKind: 'quickchart.render',
  defaultFormat: 'text',
}

export const quickChartProvider: PublicApiProviderModule = {
  manifest: {
    id: 'quickchart',
    name: 'QuickChart',
    description: 'No-auth HTTPS API that renders Chart.js configuration into chart image artifacts.',
    publicApisCategory: 'Development',
    homepageUrl: 'https://quickchart.io/',
    docsUrl: 'https://quickchart.io/documentation/',
    auth: {
      mode: 'none',
      notes: ['Public chart rendering endpoint works without API keys, OAuth, cookies, browser sessions, or scraping.'],
    },
    tags: ['development', 'chart', 'image', 'chartjs', 'rendering', 'no-auth'],
    freePlanNotes: [
      'Basic chart image URLs are usable without an API key; QuickChart offers paid features for higher-volume or advanced workflows.',
      'This provider exposes a curated simple chart builder rather than raw arbitrary Chart.js JavaScript.',
      'Width and height are capped at 2000 pixels in the CLI to keep image payloads bounded.',
    ],
  },
  operations: [renderOperation],
  endpoints: [
    {
      id: 'quickchart-render-chart',
      method: 'GET',
      urlPattern: 'https://quickchart.io/chart*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'QuickChart chart image rendering endpoint.',
      siteIds: ['public-apis-tui'],
      observedOn: '2026-05-04',
      sampleSources: [
        'https://quickchart.io/documentation/',
        'https://quickchart.io/chart?c={type:%27bar%27,data:{labels:[%27A%27,%27B%27],datasets:[{data:[1,2]}]}}',
      ],
      consumedBy: ['quickchart render'],
      notes: ['No authentication required for basic chart rendering.', 'No browser clickstream or scraping required.', 'Provider persists the rendered artifact as base64 metadata for offline replay.'],
    },
  ],
}
