import { z } from 'zod'
import { getOpenMeteoForecast, searchOpenMeteoLocations } from '../../application/usecases/openMeteo.js'
import {
  normalizeOpenMeteoForecastInput,
  normalizeOpenMeteoGeocodingInput,
  OPEN_METEO_DEFAULT_COUNT,
  OPEN_METEO_DEFAULT_FORECAST_DAYS,
  OPEN_METEO_DEFAULT_LANGUAGE,
  OPEN_METEO_DEFAULT_LATITUDE,
  OPEN_METEO_DEFAULT_LOCATION,
  OPEN_METEO_DEFAULT_LONGITUDE,
  OPEN_METEO_MAX_COUNT,
  OPEN_METEO_MAX_FORECAST_DAYS,
  type OpenMeteoForecastInput,
  type OpenMeteoGeocodingInput,
} from '../../infrastructure/openApis/openMeteoClient.js'
import type { PublicApiOperationDefinition, PublicApiProviderModule } from '../providerTypes.js'

const forecastParamsSchema = z.object({
  latitude: z.coerce.number().optional(),
  longitude: z.coerce.number().optional(),
  forecastDays: z.coerce.number().optional(),
  timezone: z.string().optional(),
}) satisfies z.ZodType<OpenMeteoForecastInput>

const geocodingParamsSchema = z.object({
  name: z.string().optional(),
  count: z.coerce.number().optional(),
  language: z.string().optional(),
  countryCode: z.string().optional(),
}) satisfies z.ZodType<OpenMeteoGeocodingInput>

const forecastOperation: PublicApiOperationDefinition<OpenMeteoForecastInput> = {
  id: 'openmeteo.forecast',
  providerId: 'openmeteo',
  name: 'Forecast',
  commandPath: ['openmeteo', 'forecast'],
  rpcMethod: 'openmeteo.forecast',
  description: 'Read current and daily weather forecast from Open-Meteo.',
  category: 'weather',
  options: [
    {
      name: 'latitude',
      flag: '--latitude <number>',
      description: `WGS84 latitude, default ${OPEN_METEO_DEFAULT_LATITUDE}`,
      exposure: 'primary',
      group: 'query',
      reason: 'Latitude is required by the documented forecast endpoint and is the primary location coordinate.',
      valueType: 'string',
      defaultValue: String(OPEN_METEO_DEFAULT_LATITUDE),
    },
    {
      name: 'longitude',
      flag: '--longitude <number>',
      description: `WGS84 longitude, default ${OPEN_METEO_DEFAULT_LONGITUDE}`,
      exposure: 'primary',
      group: 'query',
      reason: 'Longitude is required by the documented forecast endpoint and is the primary location coordinate.',
      valueType: 'string',
      defaultValue: String(OPEN_METEO_DEFAULT_LONGITUDE),
    },
    {
      name: 'forecastDays',
      flag: '--forecast-days <days>',
      description: `Forecast days, default/cap ${OPEN_METEO_DEFAULT_FORECAST_DAYS}`,
      exposure: 'primary',
      group: 'pagination',
      reason: 'Docs state forecast_days can return up to 16 days; defaulting to 16 maximizes one free request.',
      valueType: 'integer',
      defaultValue: String(OPEN_METEO_DEFAULT_FORECAST_DAYS),
    },
    {
      name: 'timezone',
      flag: '--timezone <name|auto>',
      description: 'Timezone parameter, default auto',
      exposure: 'advanced',
      group: 'presentation',
      reason: 'Timezone controls daily timestamps and is documented; auto is suitable for most terminal users.',
      defaultValue: 'auto',
    },
  ],
  paramsSchema: forecastParamsSchema,
  execute: params => getOpenMeteoForecast(params),
  normalizeParams: params => forecastParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeOpenMeteoForecastInput(params),
  resultKind: 'openmeteo.forecast',
  defaultFormat: 'text',
}

const geocodingOperation: PublicApiOperationDefinition<OpenMeteoGeocodingInput> = {
  id: 'openmeteo.geocoding',
  providerId: 'openmeteo',
  name: 'Geocoding',
  commandPath: ['openmeteo', 'geocoding'],
  rpcMethod: 'openmeteo.geocoding',
  description: 'Search global locations using Open-Meteo Geocoding API.',
  category: 'weather',
  options: [
    {
      name: 'name',
      flag: '--name <text>',
      description: `Location name or postal code, default ${OPEN_METEO_DEFAULT_LOCATION}`,
      exposure: 'primary',
      group: 'query',
      reason: 'Name is the required documented geocoding search term.',
      defaultValue: OPEN_METEO_DEFAULT_LOCATION,
    },
    {
      name: 'count',
      flag: '--count <count>',
      description: `Results to return, default ${OPEN_METEO_DEFAULT_COUNT}, cap ${OPEN_METEO_MAX_COUNT}`,
      exposure: 'primary',
      group: 'pagination',
      reason: 'Docs state up to 100 geocoding results can be retrieved; defaulting to 100 maximizes one request.',
      valueType: 'integer',
      defaultValue: String(OPEN_METEO_DEFAULT_COUNT),
    },
    {
      name: 'language',
      flag: '--language <code>',
      description: `Result language, default ${OPEN_METEO_DEFAULT_LANGUAGE}`,
      exposure: 'advanced',
      group: 'content',
      reason: 'Language is documented but secondary to location discovery.',
      defaultValue: OPEN_METEO_DEFAULT_LANGUAGE,
    },
    {
      name: 'countryCode',
      flag: '--country-code <code>',
      description: 'Optional ISO-3166 alpha-2 country filter, e.g. DE',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Country filtering is documented and useful for disambiguation.',
    },
  ],
  paramsSchema: geocodingParamsSchema,
  execute: params => searchOpenMeteoLocations(params),
  normalizeParams: params => geocodingParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeOpenMeteoGeocodingInput(params),
  resultKind: 'openmeteo.geocoding',
  defaultFormat: 'text',
}

export const openMeteoProvider: PublicApiProviderModule = {
  manifest: {
    id: 'openmeteo',
    name: 'Open-Meteo',
    description: 'No-auth HTTPS JSON weather forecast and geocoding APIs.',
    publicApisCategory: 'Weather',
    homepageUrl: 'https://open-meteo.com/',
    docsUrl: 'https://open-meteo.com/en/docs',
    auth: {
      mode: 'none',
      notes: ['Free non-commercial forecast/geocoding endpoints require no API key; commercial customer APIs use a separate keyed server.'],
    },
    tags: ['weather', 'forecast', 'geocoding', 'climate', 'no-auth', 'json'],
    freePlanNotes: [
      `Forecast defaults to ${OPEN_METEO_MAX_FORECAST_DAYS} days, the documented maximum for forecast_days.`,
      `Geocoding defaults to ${OPEN_METEO_MAX_COUNT} results, the documented maximum count.`,
      'No browser clickstream, scraping, cookies, or account setup are used.',
    ],
  },
  operations: [forecastOperation, geocodingOperation],
  endpoints: [
    {
      id: 'openmeteo-forecast',
      method: 'GET',
      urlPattern: 'https://api.open-meteo.com/v1/forecast*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Open-Meteo weather forecast endpoint returning current and daily JSON variables.',
      siteIds: ['public-apis-tui'],
      observedOn: '2026-05-04',
      sampleSources: ['https://open-meteo.com/en/docs', 'https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&forecast_days=16'],
      consumedBy: ['openmeteo forecast'],
      notes: ['No authentication required for free non-commercial endpoint.', 'Docs state forecast_days maximum is 16.'],
    },
    {
      id: 'openmeteo-geocoding-search',
      method: 'GET',
      urlPattern: 'https://geocoding-api.open-meteo.com/v1/search*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Open-Meteo geocoding endpoint returning matching locations.',
      siteIds: ['public-apis-tui'],
      observedOn: '2026-05-04',
      sampleSources: ['https://open-meteo.com/en/docs/geocoding-api', 'https://geocoding-api.open-meteo.com/v1/search?name=Berlin&count=100'],
      consumedBy: ['openmeteo geocoding'],
      notes: ['No authentication required for free non-commercial endpoint.', 'Docs state count maximum is 100.'],
    },
  ],
}
