import { z } from 'zod'
import {
  getCatFactNinjaRandomFact,
  listCatFactNinjaBreeds,
  listCatFactNinjaFacts,
  type CatFactNinjaBreedsInput,
  type CatFactNinjaFactInput,
  type CatFactNinjaListInput,
} from '../../application/usecases/catFactNinja.js'
import type { PublicApiProviderModule } from '../providerTypes.js'

const catFactParamsSchema = z.object({
  maxLength: z.number().int().optional(),
}) satisfies z.ZodType<CatFactNinjaFactInput>

const catFactsParamsSchema = z.object({
  maxLength: z.number().int().optional(),
  limit: z.number().int().optional(),
  page: z.number().int().optional(),
}) satisfies z.ZodType<CatFactNinjaListInput>

const catBreedsParamsSchema = z.object({
  limit: z.number().int().optional(),
  page: z.number().int().optional(),
}) satisfies z.ZodType<CatFactNinjaBreedsInput>

export const catFactProvider: PublicApiProviderModule = {
  manifest: {
    id: 'catfact-ninja',
    name: 'CatFact Ninja',
    description: 'No-auth HTTPS JSON API for random cat facts, paginated cat facts, and cat breeds.',
    publicApisCategory: 'Animals',
    homepageUrl: 'https://catfact.ninja/',
    docsUrl: 'https://catfact.ninja/docs',
    auth: {
      mode: 'none',
      notes: ['Public APIs README lists Auth as No; official OpenAPI docs require no API key.'],
    },
    tags: ['animals', 'cats', 'facts', 'no-auth'],
    freePlanNotes: ['No documented page-size maximum in the OpenAPI document; CLI leaves limit unset unless requested.'],
  },
  operations: [
    {
      id: 'catfact.fact',
      providerId: 'catfact-ninja',
      name: 'Random cat fact',
      commandPath: ['catfact', 'fact'],
      rpcMethod: 'catfact.fact',
      description: 'Fetch one random cat fact from CatFact Ninja.',
      category: 'animals',
      options: [
        {
          name: 'maxLength',
          flag: '--max-length <count>',
          description: 'Maximum fact length accepted by CatFact Ninja',
          exposure: 'advanced',
          group: 'content',
          reason: 'Helpful for fitting short terminal output, but not required for the default random fact use case.',
          valueType: 'integer',
        },
      ],
      paramsSchema: catFactParamsSchema,
      execute: params => getCatFactNinjaRandomFact(params),
      normalizeParams: params => catFactParamsSchema.parse(params),
      resultKind: 'catfact.fact',
      defaultFormat: 'text',
    },
    {
      id: 'catfact.facts',
      providerId: 'catfact-ninja',
      name: 'Cat facts',
      commandPath: ['catfact', 'facts'],
      rpcMethod: 'catfact.facts',
      description: 'List paginated cat facts from CatFact Ninja.',
      category: 'animals',
      options: [
        {
          name: 'maxLength',
          flag: '--max-length <count>',
          description: 'Maximum fact length accepted by CatFact Ninja',
          exposure: 'advanced',
          group: 'content',
          reason: 'Helpful for concise output, but query intent usually starts with page size.',
          valueType: 'integer',
        },
        {
          name: 'limit',
          flag: '--limit <count>',
          description: 'Page size; CatFact Ninja docs do not publish a maximum',
          exposure: 'primary',
          group: 'pagination',
          reason: 'Controls response size and terminal output length.',
          valueType: 'integer',
        },
        {
          name: 'page',
          flag: '--page <count>',
          description: 'Pagination page number, 1 or greater',
          exposure: 'advanced',
          group: 'pagination',
          reason: 'Needed to continue a paginated list without adding a separate pager UI.',
          valueType: 'integer',
        },
      ],
      paramsSchema: catFactsParamsSchema,
      execute: params => listCatFactNinjaFacts(params),
      normalizeParams: params => catFactsParamsSchema.parse(params),
      resultKind: 'catfact.facts',
      defaultFormat: 'text',
    },
    {
      id: 'catfact.breeds',
      providerId: 'catfact-ninja',
      name: 'Cat breeds',
      commandPath: ['catfact', 'breeds'],
      rpcMethod: 'catfact.breeds',
      description: 'List paginated cat breeds from CatFact Ninja.',
      category: 'animals',
      options: [
        {
          name: 'limit',
          flag: '--limit <count>',
          description: 'Page size; CatFact Ninja docs do not publish a maximum',
          exposure: 'primary',
          group: 'pagination',
          reason: 'Controls response size and terminal output length.',
          valueType: 'integer',
        },
        {
          name: 'page',
          flag: '--page <count>',
          description: 'Pagination page number, 1 or greater',
          exposure: 'advanced',
          group: 'pagination',
          reason: 'Needed to continue a paginated list without adding a separate pager UI.',
          valueType: 'integer',
        },
      ],
      paramsSchema: catBreedsParamsSchema,
      execute: params => listCatFactNinjaBreeds(params),
      normalizeParams: params => catBreedsParamsSchema.parse(params),
      resultKind: 'catfact.breeds',
      defaultFormat: 'text',
    },
  ],
  endpoints: [
    {
      id: 'catfact-ninja-fact',
      method: 'GET',
      urlPattern: 'https://catfact.ninja/fact*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'CatFact Ninja random cat fact endpoint.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://catfact.ninja/docs'],
      consumedBy: ['catfact fact'],
      notes: ['No authentication required.'],
    },
    {
      id: 'catfact-ninja-facts',
      method: 'GET',
      urlPattern: 'https://catfact.ninja/facts*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'CatFact Ninja paginated cat facts endpoint.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://catfact.ninja/docs'],
      consumedBy: ['catfact facts'],
      notes: ['No authentication required.'],
    },
    {
      id: 'catfact-ninja-breeds',
      method: 'GET',
      urlPattern: 'https://catfact.ninja/breeds*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'CatFact Ninja paginated cat breeds endpoint.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://catfact.ninja/docs'],
      consumedBy: ['catfact breeds'],
      notes: ['No authentication required.'],
    },
  ],
}
