import { z } from 'zod'
import { searchJikanAnime, type JikanAnimeInput } from '../../application/usecases/jikan.js'
import type { PublicApiProviderModule } from '../providerTypes.js'

const animeParamsSchema = z.object({
  query: z.string().min(1).optional(),
  limit: z.number().int().optional(),
  page: z.number().int().optional(),
  sfw: z.boolean().optional(),
  type: z.string().min(1).optional(),
  status: z.string().min(1).optional(),
  orderBy: z.string().min(1).optional(),
  sort: z.string().min(1).optional(),
}) satisfies z.ZodType<JikanAnimeInput>

export const jikanProvider: PublicApiProviderModule = {
  manifest: {
    id: 'jikan',
    name: 'Jikan',
    description: 'No-auth unofficial MyAnimeList REST API for anime search and metadata.',
    publicApisCategory: 'Anime',
    homepageUrl: 'https://jikan.moe',
    docsUrl: 'https://docs.api.jikan.moe/',
    auth: {
      mode: 'none',
      notes: ['Official docs state Jikan only supports unauthenticated GET read-only data.'],
    },
    tags: ['anime', 'myanimelist', 'search', 'no-auth'],
    freePlanNotes: [
      'Official docs state daily requests are unlimited, with 60 requests/minute and 3 requests/second limits.',
      'Official docs state all requests are cached for 24 hours.',
      'OpenAPI limit parameter has no documented maximum; CLI defaults to the observed API default of 25 and caps interactive output at 25.',
    ],
  },
  operations: [
    {
      id: 'jikan.anime',
      providerId: 'jikan',
      name: 'Anime search',
      commandPath: ['jikan', 'anime'],
      rpcMethod: 'jikan.anime',
      description: 'Search Jikan anime entries with curated filters from the documented /anime endpoint.',
      category: 'anime',
      options: [
        {
          name: 'query',
          flag: '--query <text>',
          description: 'Search text sent as the documented q query parameter',
          exposure: 'primary',
          group: 'query',
          reason: 'Primary user intent for anime lookup while keeping /anime browse available without a query.',
        },
        {
          name: 'limit',
          flag: '--limit <count>',
          description: 'Number of anime rows to request, capped to 25 for terminal output',
          exposure: 'primary',
          group: 'pagination',
          reason: 'Controls response size; 25 matches the current API default returned by live pagination.',
          valueType: 'integer',
          defaultValue: '25',
        },
        {
          name: 'page',
          flag: '--page <number>',
          description: 'Result page number',
          exposure: 'advanced',
          group: 'pagination',
          reason: 'Supports documented pagination without cluttering the common first-page workflow.',
          valueType: 'integer',
          defaultValue: '1',
        },
        {
          name: 'sfw',
          flag: '--sfw <true|false>',
          description: 'Filter adult entries when true',
          exposure: 'primary',
          group: 'filters',
          reason: 'Safe-for-work filtering is important for terminal defaults and scripted usage.',
          valueType: 'boolean',
          defaultValue: 'true',
        },
        {
          name: 'type',
          flag: '--type <type>',
          description: 'Anime type: tv, movie, ova, special, ona, music, cm, pv, or tv_special',
          exposure: 'advanced',
          group: 'filters',
          reason: 'Useful documented filter, but secondary to text search and result count.',
        },
        {
          name: 'status',
          flag: '--status <status>',
          description: 'Anime status: airing, complete, or upcoming',
          exposure: 'advanced',
          group: 'filters',
          reason: 'Useful documented filter for focused searches.',
        },
        {
          name: 'orderBy',
          flag: '--order-by <field>',
          description: 'Sort field such as score, popularity, members, title, or rank',
          exposure: 'advanced',
          group: 'presentation',
          reason: 'Supports result ordering while avoiding the full raw parameter surface in default help.',
        },
        {
          name: 'sort',
          flag: '--sort <direction>',
          description: 'Sort direction: asc or desc',
          exposure: 'advanced',
          group: 'presentation',
          reason: 'Only useful together with --order-by, so it is advanced.',
        },
      ],
      paramsSchema: animeParamsSchema,
      execute: params => searchJikanAnime(params),
      normalizeParams: params => animeParamsSchema.parse(params),
      resultKind: 'jikan.anime',
      defaultFormat: 'text',
    },
  ],
  endpoints: [
    {
      id: 'jikan-anime-search',
      method: 'GET',
      urlPattern: 'https://api.jikan.moe/v4/anime*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Jikan /anime endpoint returning paginated anime search and browse JSON.',
      siteIds: ['public-apis-tui'],
      sampleSources: [
        'https://docs.api.jikan.moe/',
        'https://raw.githubusercontent.com/jikan-me/jikan-rest/master/storage/api-docs/api-docs.json',
      ],
      consumedBy: ['jikan anime'],
      notes: ['No authentication required.', 'Docs state 3 requests/second and 60 requests/minute rate limits.'],
    },
  ],
}
