import { z } from 'zod'
import { listLuchtmeetnetComponents, listLuchtmeetnetConcentrations, listLuchtmeetnetMeasurements } from '../../application/usecases/luchtmeetnet.js'
import {
  LUCHTMEETNET_COMPONENTS_DEFAULT_LIMIT,
  LUCHTMEETNET_COMPONENTS_MAX_LIMIT,
  LUCHTMEETNET_CONCENTRATIONS_DEFAULT_LIMIT,
  LUCHTMEETNET_CONCENTRATIONS_MAX_LIMIT,
  LUCHTMEETNET_DEFAULT_FORMULA,
  LUCHTMEETNET_DEFAULT_LATITUDE,
  LUCHTMEETNET_DEFAULT_LONGITUDE,
  LUCHTMEETNET_DEFAULT_STATION,
  LUCHTMEETNET_MEASUREMENTS_DEFAULT_LIMIT,
  LUCHTMEETNET_MEASUREMENTS_MAX_LIMIT,
  normalizeLuchtmeetnetComponentsInput,
  normalizeLuchtmeetnetConcentrationsInput,
  normalizeLuchtmeetnetMeasurementsInput,
  type LuchtmeetnetComponentsInput,
  type LuchtmeetnetConcentrationsInput,
  type LuchtmeetnetMeasurementsInput,
} from '../../infrastructure/openApis/luchtmeetnetClient.js'
import type { PublicApiOperationDefinition, PublicApiProviderModule } from '../providerTypes.js'

const componentsParamsSchema = z.object({
  limit: z.coerce.number().optional(),
}) satisfies z.ZodType<LuchtmeetnetComponentsInput>

const measurementsParamsSchema = z.object({
  stationNumber: z.string().optional(),
  formula: z.string().optional(),
  limit: z.coerce.number().optional(),
}) satisfies z.ZodType<LuchtmeetnetMeasurementsInput>

const concentrationsParamsSchema = z.object({
  formula: z.string().optional(),
  latitude: z.coerce.number().optional(),
  longitude: z.coerce.number().optional(),
  limit: z.coerce.number().optional(),
}) satisfies z.ZodType<LuchtmeetnetConcentrationsInput>

const componentsOperation: PublicApiOperationDefinition<LuchtmeetnetComponentsInput> = {
  id: 'luchtmeetnet.components',
  providerId: 'luchtmeetnet',
  name: 'Components',
  commandPath: ['luchtmeetnet', 'components'],
  rpcMethod: 'luchtmeetnet.components',
  description: 'List Luchtmeetnet air-quality components such as NO2, PM10, and PM2.5.',
  category: 'environment',
  options: [
    {
      name: 'limit',
      flag: '--limit <count>',
      description: `Components to show, default/cap ${LUCHTMEETNET_COMPONENTS_DEFAULT_LIMIT}`,
      exposure: 'primary',
      group: 'pagination',
      reason: 'The components endpoint currently returns one page of 13 formulas; default uses that full page.',
      valueType: 'integer',
      defaultValue: String(LUCHTMEETNET_COMPONENTS_DEFAULT_LIMIT),
    },
  ],
  paramsSchema: componentsParamsSchema,
  execute: params => listLuchtmeetnetComponents(params),
  normalizeParams: params => componentsParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeLuchtmeetnetComponentsInput(params),
  resultKind: 'luchtmeetnet.components',
  defaultFormat: 'text',
}

const measurementsOperation: PublicApiOperationDefinition<LuchtmeetnetMeasurementsInput> = {
  id: 'luchtmeetnet.measurements',
  providerId: 'luchtmeetnet',
  name: 'Measurements',
  commandPath: ['luchtmeetnet', 'measurements'],
  rpcMethod: 'luchtmeetnet.measurements',
  description: 'Fetch recent measured hourly air-quality values for one station and formula.',
  category: 'environment',
  options: [
    {
      name: 'stationNumber',
      flag: '--station-number <code>',
      description: `Station number, default ${LUCHTMEETNET_DEFAULT_STATION}`,
      exposure: 'primary',
      group: 'query',
      reason: 'Measurements can be scoped to one official station number for stable, useful output.',
      defaultValue: LUCHTMEETNET_DEFAULT_STATION,
    },
    {
      name: 'formula',
      flag: '--formula <code>',
      description: `Component formula, default ${LUCHTMEETNET_DEFAULT_FORMULA}`,
      exposure: 'primary',
      group: 'filters',
      reason: 'Formula selection is the main pollutant filter and keeps cache keys explicit.',
      defaultValue: LUCHTMEETNET_DEFAULT_FORMULA,
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: `Measurements to show, default/cap ${LUCHTMEETNET_MEASUREMENTS_DEFAULT_LIMIT}`,
      exposure: 'primary',
      group: 'pagination',
      reason: 'The live default query returns up to 167 recent hourly rows; default uses that maximum to maximize a limited request.',
      valueType: 'integer',
      defaultValue: String(LUCHTMEETNET_MEASUREMENTS_DEFAULT_LIMIT),
    },
  ],
  paramsSchema: measurementsParamsSchema,
  execute: params => listLuchtmeetnetMeasurements(params),
  normalizeParams: params => measurementsParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeLuchtmeetnetMeasurementsInput(params),
  resultKind: 'luchtmeetnet.measurements',
  defaultFormat: 'text',
}

const concentrationsOperation: PublicApiOperationDefinition<LuchtmeetnetConcentrationsInput> = {
  id: 'luchtmeetnet.concentrations',
  providerId: 'luchtmeetnet',
  name: 'Concentrations',
  commandPath: ['luchtmeetnet', 'concentrations'],
  rpcMethod: 'luchtmeetnet.concentrations',
  description: 'Fetch current and predicted concentration values for one component and location.',
  category: 'environment',
  options: [
    {
      name: 'formula',
      flag: '--formula <code>',
      description: `Component formula, default ${LUCHTMEETNET_DEFAULT_FORMULA}`,
      exposure: 'primary',
      group: 'filters',
      reason: 'Formula selection chooses the pollutant for current/predicted concentration analysis.',
      defaultValue: LUCHTMEETNET_DEFAULT_FORMULA,
    },
    {
      name: 'latitude',
      flag: '--latitude <number>',
      description: `Latitude, default ${LUCHTMEETNET_DEFAULT_LATITUDE}`,
      exposure: 'primary',
      group: 'query',
      reason: 'Concentrations endpoint requires a WGS84 location.',
      valueType: 'string',
      defaultValue: String(LUCHTMEETNET_DEFAULT_LATITUDE),
    },
    {
      name: 'longitude',
      flag: '--longitude <number>',
      description: `Longitude, default ${LUCHTMEETNET_DEFAULT_LONGITUDE}`,
      exposure: 'primary',
      group: 'query',
      reason: 'Concentrations endpoint requires a WGS84 location.',
      valueType: 'string',
      defaultValue: String(LUCHTMEETNET_DEFAULT_LONGITUDE),
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: `Concentration rows to show, default/cap ${LUCHTMEETNET_CONCENTRATIONS_DEFAULT_LIMIT}`,
      exposure: 'primary',
      group: 'pagination',
      reason: 'The live location query returns 19 current/predicted rows; default uses that maximum to maximize a limited request.',
      valueType: 'integer',
      defaultValue: String(LUCHTMEETNET_CONCENTRATIONS_DEFAULT_LIMIT),
    },
  ],
  paramsSchema: concentrationsParamsSchema,
  execute: params => listLuchtmeetnetConcentrations(params),
  normalizeParams: params => concentrationsParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeLuchtmeetnetConcentrationsInput(params),
  resultKind: 'luchtmeetnet.concentrations',
  defaultFormat: 'text',
}

export const luchtmeetnetProvider: PublicApiProviderModule = {
  manifest: {
    id: 'luchtmeetnet',
    name: 'Luchtmeetnet',
    description: 'No-auth Dutch air-quality components, measured values, and concentration forecasts.',
    publicApisCategory: 'Environment',
    homepageUrl: 'https://www.luchtmeetnet.nl/',
    docsUrl: 'https://api-docs.luchtmeetnet.nl/',
    auth: {
      mode: 'none',
      notes: ['Official open_api endpoints work without API key, OAuth, cookies, browser session, or account setup.'],
    },
    tags: ['environment', 'air-quality', 'netherlands', 'rivm', 'no-auth', 'json'],
    freePlanNotes: [
      'Official docs state the API base is https://api.luchtmeetnet.nl/open_api.',
      `Defaults use the observed maximum useful rows: ${LUCHTMEETNET_COMPONENTS_MAX_LIMIT} components, ${LUCHTMEETNET_MEASUREMENTS_MAX_LIMIT} measurements, and ${LUCHTMEETNET_CONCENTRATIONS_MAX_LIMIT} concentration rows.`,
    ],
  },
  operations: [componentsOperation, measurementsOperation, concentrationsOperation],
  endpoints: [
    {
      id: 'luchtmeetnet-components',
      method: 'GET',
      urlPattern: 'https://api.luchtmeetnet.nl/open_api/components*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Luchtmeetnet component list endpoint.',
      siteIds: ['public-apis-tui'],
      observedOn: '2026-05-04',
      sampleSources: ['https://api-docs.luchtmeetnet.nl/', 'https://api.luchtmeetnet.nl/open_api/components?page=1&order_by=formula'],
      consumedBy: ['luchtmeetnet components'],
      notes: ['No API key required.', 'Returns current component formulas and names.'],
    },
    {
      id: 'luchtmeetnet-measurements',
      method: 'GET',
      urlPattern: 'https://api.luchtmeetnet.nl/open_api/measurements*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Luchtmeetnet measured values endpoint.',
      siteIds: ['public-apis-tui'],
      observedOn: '2026-05-04',
      sampleSources: ['https://api-docs.luchtmeetnet.nl/', 'https://api.luchtmeetnet.nl/open_api/measurements?station_number=NL01485&formula=NO2&page=1'],
      consumedBy: ['luchtmeetnet measurements'],
      notes: ['No API key required.', 'Docs warn time ranges larger than seven days may redirect to an adjusted range; CLI uses current default range only.'],
    },
    {
      id: 'luchtmeetnet-concentrations',
      method: 'GET',
      urlPattern: 'https://api.luchtmeetnet.nl/open_api/concentrations*',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'Luchtmeetnet current and predicted concentration endpoint.',
      siteIds: ['public-apis-tui'],
      observedOn: '2026-05-04',
      sampleSources: ['https://api-docs.luchtmeetnet.nl/', 'https://api.luchtmeetnet.nl/open_api/concentrations?formula=no2&longitude=4.458807&latitude=51.924452'],
      consumedBy: ['luchtmeetnet concentrations'],
      notes: ['No API key required.', 'Returns current and predicted concentration rows for a WGS84 coordinate.'],
    },
  ],
}
