import { z } from 'zod'
import {
  getApisGuruMetrics,
  listApisGuruProviders,
  normalizeApisGuruProvidersInput,
  normalizeApisGuruSearchInput,
  searchApisGuru,
  type ApisGuruProvidersInput,
  type ApisGuruSearchInput,
} from '../../application/usecases/apisGuru.js'
import type { PublicApiOperationDefinition, PublicApiProviderModule } from '../providerTypes.js'

const providersParamsSchema = z.object({
  query: z.string().min(1).optional(),
  limit: z.number().int().optional(),
}) satisfies z.ZodType<ApisGuruProvidersInput>

const searchParamsSchema = z.object({
  query: z.string().min(1).optional(),
  category: z.string().min(1).optional(),
  provider: z.string().min(1).optional(),
  includeUnofficial: z.boolean().optional(),
  sort: z.enum(['updated', 'title', 'provider']).optional(),
  limit: z.number().int().optional(),
}) satisfies z.ZodType<ApisGuruSearchInput>

const providersOperation: PublicApiOperationDefinition<ApisGuruProvidersInput> = {
  id: 'apisguru.providers',
  providerId: 'apisguru',
  name: 'Providers',
  commandPath: ['apisguru', 'providers'],
  rpcMethod: 'apisguru.providers',
  description: 'List APIs.guru directory providers with optional substring filtering.',
  category: 'development',
  options: [
    {
      name: 'query',
      flag: '--query <text>',
      description: 'Filter provider hostnames by substring',
      exposure: 'primary',
      group: 'query',
      reason: 'Provider names are the primary lookup surface for the documented /providers.json endpoint.',
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: 'Providers to show, default 20, CLI cap 100',
      exposure: 'primary',
      group: 'pagination',
      reason: 'The upstream endpoint has no pagination; a bounded limit keeps terminal output and cache size predictable.',
      valueType: 'integer',
      defaultValue: '20',
    },
  ],
  paramsSchema: providersParamsSchema,
  execute: params => listApisGuruProviders(params),
  normalizeParams: params => providersParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeApisGuruProvidersInput(params),
  resultKind: 'apisguru.providers',
  defaultFormat: 'text',
}

const searchOperation: PublicApiOperationDefinition<ApisGuruSearchInput> = {
  id: 'apisguru.search',
  providerId: 'apisguru',
  name: 'Search',
  commandPath: ['apisguru', 'search'],
  rpcMethod: 'apisguru.search',
  description: 'Search cached APIs.guru OpenAPI directory metadata from /list.json.',
  category: 'development',
  options: [
    {
      name: 'query',
      flag: '--query <text>',
      description: 'Search API id, title, service, description, and categories',
      exposure: 'primary',
      group: 'query',
      reason: 'APIs.guru has no server search parameter, so client-side search is the main CLI discovery intent.',
    },
    {
      name: 'category',
      flag: '--category <name>',
      description: 'Filter by APIs.guru category, e.g. developer_tools',
      exposure: 'primary',
      group: 'filters',
      reason: 'Categories are cached in each API object and provide high-signal terminal filtering.',
    },
    {
      name: 'provider',
      flag: '--provider <host>',
      description: 'Filter by provider hostname substring',
      exposure: 'primary',
      group: 'filters',
      reason: 'Provider filtering maps directly to APIs.guru API IDs and supports focused discovery.',
    },
    {
      name: 'includeUnofficial',
      flag: '--include-unofficial <true|false>',
      description: 'Include unofficial specs, default false',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Unofficial specs are useful but lower confidence; hiding them by default protects research quality.',
      valueType: 'boolean',
      defaultValue: 'false',
    },
    {
      name: 'sort',
      flag: '--sort <updated|title|provider>',
      description: 'Sort shown matches, default updated',
      exposure: 'advanced',
      group: 'presentation',
      reason: 'Sorting is a CLI projection choice over the static upstream list, useful after query narrowing.',
      defaultValue: 'updated',
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: 'APIs to show, default 20, CLI cap 100',
      exposure: 'primary',
      group: 'pagination',
      reason: 'The upstream list is a large unpaginated object; a bounded limit keeps output and persistence predictable.',
      valueType: 'integer',
      defaultValue: '20',
    },
  ],
  paramsSchema: searchParamsSchema,
  execute: params => searchApisGuru(params),
  normalizeParams: params => searchParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeApisGuruSearchInput(params),
  resultKind: 'apisguru.search',
  defaultFormat: 'text',
}

const metricsOperation: PublicApiOperationDefinition<Record<string, never>> = {
  id: 'apisguru.metrics',
  providerId: 'apisguru',
  name: 'Metrics',
  commandPath: ['apisguru', 'metrics'],
  rpcMethod: 'apisguru.metrics',
  description: 'Show APIs.guru directory counts and top provider metrics.',
  category: 'development',
  options: [],
  paramsSchema: z.object({}).strict(),
  execute: () => getApisGuruMetrics(),
  normalizeParams: () => ({}),
  createCacheKeyParams: () => ({}),
  resultKind: 'apisguru.metrics',
  defaultFormat: 'text',
}

export const apisGuruProvider: PublicApiProviderModule = {
  manifest: {
    id: 'apisguru',
    name: 'APIs.guru',
    description: 'No-auth HTTPS JSON directory of public OpenAPI and Swagger definitions.',
    publicApisCategory: 'Development',
    homepageUrl: 'https://apis.guru/api-doc/',
    docsUrl: 'https://api.apis.guru/v2/openapi.yaml',
    auth: {
      mode: 'none',
      notes: ['Official OpenAPI definition declares security: [] and live HTTPS JSON probes require no API key.'],
    },
    tags: ['development', 'openapi', 'swagger', 'api-directory', 'no-auth', 'json'],
    freePlanNotes: [
      'Rate limits are not documented in the official OpenAPI definition.',
      'The list and providers endpoints are unpaginated; CLI defaults to 20 and caps at 100 shown items.',
      'Search filters /list.json client-side because the upstream API does not expose query parameters for that endpoint.',
    ],
  },
  operations: [providersOperation, searchOperation, metricsOperation],
  endpoints: [
    {
      id: 'apisguru-providers',
      method: 'GET',
      urlPattern: 'https://api.apis.guru/v2/providers.json',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'APIs.guru provider hostname list.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://api.apis.guru/v2/openapi.yaml', 'https://api.apis.guru/v2/providers.json'],
      consumedBy: ['apisguru providers'],
      notes: ['No authentication required; official OpenAPI declares security: [].', 'No browser clickstream or scraping required.'],
    },
    {
      id: 'apisguru-list',
      method: 'GET',
      urlPattern: 'https://api.apis.guru/v2/list.json',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'APIs.guru API directory list keyed by API id.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://api.apis.guru/v2/openapi.yaml', 'https://api.apis.guru/v2/list.json'],
      consumedBy: ['apisguru search'],
      notes: ['No authentication required; endpoint is unpaginated and filtered client-side by CLI.', 'No browser clickstream or scraping required.'],
    },
    {
      id: 'apisguru-metrics',
      method: 'GET',
      urlPattern: 'https://api.apis.guru/v2/metrics.json',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'APIs.guru aggregate directory metrics.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://api.apis.guru/v2/openapi.yaml', 'https://api.apis.guru/v2/metrics.json'],
      consumedBy: ['apisguru metrics'],
      notes: ['No authentication required; official OpenAPI declares security: [].', 'No browser clickstream or scraping required.'],
    },
  ],
}
