import { z } from 'zod'
import {
  LAUNCH_LIBRARY2_DEFAULT_EVENT_ORDERING,
  LAUNCH_LIBRARY2_DEFAULT_LAUNCH_ORDERING,
  LAUNCH_LIBRARY2_DEFAULT_LIMIT,
  LAUNCH_LIBRARY2_MAX_LIMIT,
  LAUNCH_LIBRARY2_MAX_OFFSET,
  listLaunchLibrary2Events,
  listLaunchLibrary2Launches,
  normalizeLaunchLibrary2EventsInput,
  normalizeLaunchLibrary2LaunchesInput,
  type LaunchLibrary2EventsInput,
  type LaunchLibrary2LaunchesInput,
} from '../../application/usecases/launchLibrary2.js'
import type {
  PublicApiOperationDefinition,
  PublicApiProviderModule,
} from '../providerTypes.js'

const launchesParamsSchema = z.object({
  search: z.string().optional(),
  lsp: z.string().optional(),
  start: z.string().optional(),
  end: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  ordering: z.string().optional(),
}) satisfies z.ZodType<LaunchLibrary2LaunchesInput>

const eventsParamsSchema = z.object({
  search: z.string().optional(),
  start: z.string().optional(),
  end: z.string().optional(),
  hideRecentPrevious: z.boolean().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  ordering: z.string().optional(),
}) satisfies z.ZodType<LaunchLibrary2EventsInput>

const launchesOperation: PublicApiOperationDefinition<LaunchLibrary2LaunchesInput> = {
  id: 'launchlibrary2.launches',
  providerId: 'launchlibrary2',
  name: 'Upcoming launches',
  commandPath: ['launchlibrary2', 'launches'],
  rpcMethod: 'launchlibrary2.launches',
  description: 'List upcoming Launch Library 2 rocket launches.',
  category: 'science',
  options: [
    {
      name: 'search',
      flag: '--search <text>',
      description: 'Search launch names, missions, rockets, and providers.',
      exposure: 'primary',
      group: 'query',
      reason: 'Maps to the documented upcoming launches search parameter.',
      valueType: 'string',
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: [
        `Rows to show, 1-${LAUNCH_LIBRARY2_MAX_LIMIT},`,
        `default ${LAUNCH_LIBRARY2_DEFAULT_LIMIT}.`,
      ].join(' '),
      exposure: 'primary',
      group: 'pagination',
      reason: 'Uses the documented max while defaulting lower for no-auth rate limits.',
      valueType: 'integer',
      defaultValue: String(LAUNCH_LIBRARY2_DEFAULT_LIMIT),
    },
    {
      name: 'offset',
      flag: '--offset <count>',
      description: `Rows to skip, 0-${LAUNCH_LIBRARY2_MAX_OFFSET}, default 0.`,
      exposure: 'primary',
      group: 'pagination',
      reason: 'Maps to the documented list pagination offset parameter.',
      valueType: 'integer',
      defaultValue: '0',
    },
    {
      name: 'lsp',
      flag: '--lsp <name>',
      description: 'Filter by launch service provider name.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Maps to documented lsp__name without exposing every agency filter.',
      valueType: 'string',
    },
    {
      name: 'start',
      flag: '--start <iso>',
      description: 'Earliest launch NET date-time, YYYY-MM-DD or UTC ISO.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Maps to documented net__gte for quota-conscious date windows.',
      valueType: 'string',
    },
    {
      name: 'end',
      flag: '--end <iso>',
      description: 'Latest launch NET date-time, YYYY-MM-DD or UTC ISO.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Maps to documented net__lte for quota-conscious date windows.',
      valueType: 'string',
    },
    {
      name: 'ordering',
      flag: '--ordering <field>',
      description: [
        'Ordering: net, -net, last_updated, -last_updated;',
        `default ${LAUNCH_LIBRARY2_DEFAULT_LAUNCH_ORDERING}.`,
      ].join(' '),
      exposure: 'advanced',
      group: 'presentation',
      reason: 'Curated documented ordering fields useful for launch browsing.',
      valueType: 'string',
      defaultValue: LAUNCH_LIBRARY2_DEFAULT_LAUNCH_ORDERING,
    },
  ],
  paramsSchema: launchesParamsSchema,
  execute: params => listLaunchLibrary2Launches(params),
  normalizeParams: params => launchesParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeLaunchLibrary2LaunchesInput(params),
  resultKind: 'launchlibrary2.launches',
  defaultFormat: 'text',
}

const eventsOperation: PublicApiOperationDefinition<LaunchLibrary2EventsInput> = {
  id: 'launchlibrary2.events',
  providerId: 'launchlibrary2',
  name: 'Upcoming events',
  commandPath: ['launchlibrary2', 'events'],
  rpcMethod: 'launchlibrary2.events',
  description: 'List upcoming Launch Library 2 spaceflight events.',
  category: 'science',
  options: [
    {
      name: 'search',
      flag: '--search <text>',
      description: 'Search event names.',
      exposure: 'primary',
      group: 'query',
      reason: 'Maps to the documented upcoming events search parameter.',
      valueType: 'string',
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: [
        `Rows to show, 1-${LAUNCH_LIBRARY2_MAX_LIMIT},`,
        `default ${LAUNCH_LIBRARY2_DEFAULT_LIMIT}.`,
      ].join(' '),
      exposure: 'primary',
      group: 'pagination',
      reason: 'Uses the documented max while defaulting lower for no-auth rate limits.',
      valueType: 'integer',
      defaultValue: String(LAUNCH_LIBRARY2_DEFAULT_LIMIT),
    },
    {
      name: 'offset',
      flag: '--offset <count>',
      description: `Rows to skip, 0-${LAUNCH_LIBRARY2_MAX_OFFSET}, default 0.`,
      exposure: 'primary',
      group: 'pagination',
      reason: 'Maps to the documented list pagination offset parameter.',
      valueType: 'integer',
      defaultValue: '0',
    },
    {
      name: 'start',
      flag: '--start <iso>',
      description: 'Earliest event date-time, YYYY-MM-DD or UTC ISO.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Maps to documented date__gte for quota-conscious date windows.',
      valueType: 'string',
    },
    {
      name: 'end',
      flag: '--end <iso>',
      description: 'Latest event date-time, YYYY-MM-DD or UTC ISO.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Maps to documented date__lte for quota-conscious date windows.',
      valueType: 'string',
    },
    {
      name: 'hideRecentPrevious',
      flag: '--hide-recent-previous <true|false>',
      description: 'Hide recently previous events included by upstream convenience.',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Maps to the documented hide_recent_previous event filter.',
      valueType: 'boolean',
      defaultValue: 'false',
    },
    {
      name: 'ordering',
      flag: '--ordering <field>',
      description: [
        'Ordering: date, -date, last_updated, -last_updated;',
        `default ${LAUNCH_LIBRARY2_DEFAULT_EVENT_ORDERING}.`,
      ].join(' '),
      exposure: 'advanced',
      group: 'presentation',
      reason: 'Curated documented ordering fields useful for event browsing.',
      valueType: 'string',
      defaultValue: LAUNCH_LIBRARY2_DEFAULT_EVENT_ORDERING,
    },
  ],
  paramsSchema: eventsParamsSchema,
  execute: params => listLaunchLibrary2Events(params),
  normalizeParams: params => eventsParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeLaunchLibrary2EventsInput(params),
  resultKind: 'launchlibrary2.events',
  defaultFormat: 'text',
}

export const launchLibrary2Provider: PublicApiProviderModule = {
  manifest: {
    id: 'launchlibrary2',
    name: 'Launch Library 2',
    description: [
      'No-auth HTTPS JSON access to The Space Devs Launch Library 2',
      'upcoming launches and spaceflight events.',
    ].join(' '),
    publicApisCategory: 'Science & Math',
    homepageUrl: 'https://thespacedevs.com/llapi',
    docsUrl: 'https://ll.thespacedevs.com/2.3.0/swagger/',
    auth: {
      mode: 'none',
      notes: [
        [
          'Selected v2.3.0 GET endpoints return JSON without API key, OAuth,',
          'cookies, account setup, or browser session requirements.',
        ].join(' '),
        'API keys are documented only for higher rate limits and are not used.',
      ],
    },
    tags: ['science', 'spaceflight', 'launches', 'events', 'no-auth', 'json'],
    freePlanNotes: [
      'No-auth requests are free and documented as rate-limited to 15 calls/hour.',
      'The documented list limit max is 100; CLI default is lower for no-auth use.',
    ],
  },
  operations: [launchesOperation, eventsOperation],
  endpoints: [
    {
      id: 'launchlibrary2-upcoming-launches',
      method: 'GET',
      urlPattern: 'https://ll.thespacedevs.com/2.3.0/launches/upcoming/*',
      category: 'public-apis:science',
      evidenceStatus: 'confirmed',
      observedOn: '2026-05-11',
      description: 'Launch Library 2 upcoming launches JSON endpoint.',
      siteIds: ['public-apis-tui'],
      sampleSources: [
        'https://thespacedevs.com/llapi',
        'https://ll.thespacedevs.com/2.3.0/schema/',
        'https://ll.thespacedevs.com/2.3.0/launches/upcoming/?limit=2',
      ],
      consumedBy: ['public-apis apis run launchlibrary2.launches'],
      notes: [
        'No authentication required in live probes.',
        'CLI exposes curated search, date, provider, ordering, and pagination.',
      ],
    },
    {
      id: 'launchlibrary2-upcoming-events',
      method: 'GET',
      urlPattern: 'https://ll.thespacedevs.com/2.3.0/events/upcoming/*',
      category: 'public-apis:science',
      evidenceStatus: 'confirmed',
      observedOn: '2026-05-11',
      description: 'Launch Library 2 upcoming spaceflight events JSON endpoint.',
      siteIds: ['public-apis-tui'],
      sampleSources: [
        'https://thespacedevs.com/llapi',
        'https://ll.thespacedevs.com/2.3.0/schema/',
        'https://ll.thespacedevs.com/2.3.0/events/upcoming/?limit=2',
      ],
      consumedBy: ['public-apis apis run launchlibrary2.events'],
      notes: [
        'No authentication required in live probes.',
        'CLI exposes curated search, date, ordering, and pagination.',
      ],
    },
  ],
}

export type {
  LaunchLibrary2EventsInput,
  LaunchLibrary2LaunchesInput,
} from '../../application/usecases/launchLibrary2.js'
