import { z } from 'zod'
import {
  getCdnjsLibrary,
  getCdnjsVersion,
  normalizeCdnjsLibraryInput,
  normalizeCdnjsSearchInput,
  normalizeCdnjsVersionInput,
  searchCdnjsLibraries,
  type CdnjsLibraryInput,
  type CdnjsSearchInput,
  type CdnjsVersionInput,
} from '../../application/usecases/cdnjs.js'
import type { PublicApiOperationDefinition, PublicApiProviderModule } from '../providerTypes.js'

const searchParamsSchema = z.object({
  query: z.string().min(1).optional(),
  searchFields: z.string().min(1).optional(),
  limit: z.number().int().optional(),
}) satisfies z.ZodType<CdnjsSearchInput>

const libraryParamsSchema = z.object({
  name: z.string().min(1).optional(),
  versionLimit: z.number().int().optional(),
  fileLimit: z.number().int().optional(),
}) satisfies z.ZodType<CdnjsLibraryInput>

const versionParamsSchema = z.object({
  name: z.string().min(1).optional(),
  version: z.string().min(1).optional(),
  fileLimit: z.number().int().optional(),
}) satisfies z.ZodType<CdnjsVersionInput>

const searchOperation: PublicApiOperationDefinition<CdnjsSearchInput> = {
  id: 'cdnjs.search',
  providerId: 'cdnjs',
  name: 'Search',
  commandPath: ['cdnjs', 'search'],
  rpcMethod: 'cdnjs.search',
  description: 'Search CDNJS library metadata from the public CDNJS API.',
  category: 'development',
  options: [
    {
      name: 'query',
      flag: '--query <text>',
      description: 'Library search text, default jquery',
      exposure: 'primary',
      group: 'query',
      reason: 'Search is the primary documented CDNJS discovery parameter.',
      defaultValue: 'jquery',
    },
    {
      name: 'searchFields',
      flag: '--search-fields <names>',
      description: 'Comma-separated search fields, default name,description,keywords',
      exposure: 'advanced',
      group: 'filters',
      reason: 'Docs expose search_fields; keeping it advanced avoids overwhelming the common search path.',
      defaultValue: 'name,description,keywords',
    },
    {
      name: 'limit',
      flag: '--limit <count>',
      description: 'Libraries to request/show, default 1000, CLI cap 1000',
      exposure: 'primary',
      group: 'pagination',
      reason: 'Docs expose limit but no maximum; default/cap 1000 maximizes one free request while bounding output and cache size.',
      valueType: 'integer',
      defaultValue: '1000',
    },
  ],
  paramsSchema: searchParamsSchema,
  execute: params => searchCdnjsLibraries(params),
  normalizeParams: params => searchParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeCdnjsSearchInput(params),
  resultKind: 'cdnjs.search',
  defaultFormat: 'text',
}

const libraryOperation: PublicApiOperationDefinition<CdnjsLibraryInput> = {
  id: 'cdnjs.library',
  providerId: 'cdnjs',
  name: 'Library',
  commandPath: ['cdnjs', 'library'],
  rpcMethod: 'cdnjs.library',
  description: 'Fetch one CDNJS library with versions, files, SRI, and project metadata.',
  category: 'development',
  options: [
    {
      name: 'name',
      flag: '--name <library>',
      description: 'Library name, default jquery',
      exposure: 'primary',
      group: 'query',
      reason: 'The documented /libraries/{library} endpoint is library-name addressed.',
      defaultValue: 'jquery',
    },
    {
      name: 'versionLimit',
      flag: '--version-limit <count>',
      description: 'Versions to show from the unpaginated assets list, default 20, CLI cap 200',
      exposure: 'primary',
      group: 'pagination',
      reason: 'The library endpoint can return many assets; a version limit keeps TUI and cache sizes bounded.',
      valueType: 'integer',
      defaultValue: '20',
    },
    {
      name: 'fileLimit',
      flag: '--file-limit <count>',
      description: 'Files to show per version, default 50, CLI cap 500',
      exposure: 'advanced',
      group: 'pagination',
      reason: 'Files are nested under each asset; exposing a cap protects terminal readability for large libraries.',
      valueType: 'integer',
      defaultValue: '50',
    },
  ],
  paramsSchema: libraryParamsSchema,
  execute: params => getCdnjsLibrary(params),
  normalizeParams: params => libraryParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeCdnjsLibraryInput(params),
  resultKind: 'cdnjs.library',
  defaultFormat: 'text',
}

const versionOperation: PublicApiOperationDefinition<CdnjsVersionInput> = {
  id: 'cdnjs.version',
  providerId: 'cdnjs',
  name: 'Version',
  commandPath: ['cdnjs', 'version'],
  rpcMethod: 'cdnjs.version',
  description: 'Fetch CDNJS files and SRI hashes for one library version.',
  category: 'development',
  options: [
    {
      name: 'name',
      flag: '--name <library>',
      description: 'Library name, default jquery',
      exposure: 'primary',
      group: 'query',
      reason: 'The documented version endpoint is library-name addressed.',
      defaultValue: 'jquery',
    },
    {
      name: 'version',
      flag: '--version <version>',
      description: 'Library version, default 3.7.1',
      exposure: 'primary',
      group: 'query',
      reason: 'The documented version endpoint requires an explicit version path segment.',
      defaultValue: '3.7.1',
    },
    {
      name: 'fileLimit',
      flag: '--file-limit <count>',
      description: 'Files to show, default 50, CLI cap 500',
      exposure: 'primary',
      group: 'pagination',
      reason: 'The version endpoint returns an unpaginated file list; a cap keeps output predictable.',
      valueType: 'integer',
      defaultValue: '50',
    },
  ],
  paramsSchema: versionParamsSchema,
  execute: params => getCdnjsVersion(params),
  normalizeParams: params => versionParamsSchema.parse(params),
  createCacheKeyParams: params => normalizeCdnjsVersionInput(params),
  resultKind: 'cdnjs.version',
  defaultFormat: 'text',
}

export const cdnjsProvider: PublicApiProviderModule = {
  manifest: {
    id: 'cdnjs',
    name: 'CDNJS',
    description: 'No-auth HTTPS JSON API for CDNJS library, version, file, and SRI metadata.',
    publicApisCategory: 'Development',
    homepageUrl: 'https://cdnjs.com/',
    docsUrl: 'https://cdnjs.com/api',
    auth: {
      mode: 'none',
      notes: ['Official API page documents public HTTPS JSON endpoints and live probes require no API key.'],
    },
    tags: ['development', 'cdn', 'javascript', 'libraries', 'sri', 'no-auth', 'json'],
    freePlanNotes: [
      'Rate limits are not documented in the CDNJS API page.',
      'Docs expose limit for search without a documented maximum; CLI defaults/caps at 1000 to maximize a single request while bounding cache/output size.',
      'Library and version endpoints return unpaginated nested file lists; CLI exposes explicit version/file caps.',
    ],
  },
  operations: [searchOperation, libraryOperation, versionOperation],
  endpoints: [
    {
      id: 'cdnjs-libraries',
      method: 'GET',
      urlPattern: 'regex:^https://api\\.cdnjs\\.com/libraries(?:\\?.*)?$',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'CDNJS library search endpoint.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://cdnjs.com/api', 'https://api.cdnjs.com/libraries?search=jquery&limit=3'],
      consumedBy: ['cdnjs search'],
      notes: ['No authentication required; no browser clickstream or scraping required.', 'Search uses documented search, search_fields, fields, and limit parameters.'],
    },
    {
      id: 'cdnjs-library',
      method: 'GET',
      urlPattern: 'regex:^https://api\\.cdnjs\\.com/libraries/[^/?]+(?:\\?.*)?$',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'CDNJS single library metadata endpoint.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://cdnjs.com/api', 'https://api.cdnjs.com/libraries/jquery'],
      consumedBy: ['cdnjs library'],
      notes: ['No authentication required; fields parameter is documented.', 'No browser clickstream or scraping required.'],
    },
    {
      id: 'cdnjs-version',
      method: 'GET',
      urlPattern: 'regex:^https://api\\.cdnjs\\.com/libraries/[^/]+/[^/?]+(?:\\?.*)?$',
      category: 'open-api',
      evidenceStatus: 'confirmed',
      description: 'CDNJS single library version file/SRI endpoint.',
      siteIds: ['public-apis-tui'],
      sampleSources: ['https://cdnjs.com/api', 'https://api.cdnjs.com/libraries/jquery/3.7.1'],
      consumedBy: ['cdnjs version'],
      notes: ['No authentication required; fields parameter is documented.', 'No browser clickstream or scraping required.'],
    },
  ],
}
